# cAPTure: canonical packet preparation

This CPU-only notebook converts the completed Gate-0 audit Parquet files into the window-independent candidate `capture_packet_v1` schema. It reads the existing files from Drive, processes one scenario at a time, and writes checksum-verified prepared artifacts back to Drive. It does not download source CSVs, assign packets to windows, compute training weights, or train a model.

Run `SMOKE` first. Review the real-data transformations before approving and running `FULL_DEV`.

## 1. Mount Drive and load the project

In [1]:
from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
import json
import os
import shutil
import subprocess
import sys

REPOSITORY_URL = "https://github.com/tatipar/temporalgnn-nids.git"
REPOSITORY_BRANCH = "feat/capture-feasibility"
PROJECT_ROOT = Path("/content/temporalgnn-nids")
DRIVE_ROOT = Path("/content/drive/MyDrive/capture_gate0")
LOCAL_ROOT = Path("/content/capture_prepare_work")

if not PROJECT_ROOT.exists():
    subprocess.run(
        ["git", "clone", "--branch", REPOSITORY_BRANCH, "--single-branch",
         REPOSITORY_URL, str(PROJECT_ROOT)],
        check=True,
    )

required_files = [
    PROJECT_ROOT / "code/python/utils/capture_prepare.py",
    PROJECT_ROOT / "code/python/tests/test_capture_prepare.py",
    PROJECT_ROOT / "configs/capture_packet_schema_v1.yaml",
    PROJECT_ROOT / "configs/capture_experiment_v1.yaml",
    PROJECT_ROOT / "code/python/requirements-capture.txt",
]
missing_files = [str(path) for path in required_files if not path.exists()]
if missing_files:
    raise FileNotFoundError(f"Update the repository copy first: {missing_files}")

subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", "-r",
     str(PROJECT_ROOT / "code/python/requirements-capture.txt")],
    check=True,
)
sys.path.insert(0, str(PROJECT_ROOT / "code/python"))
LOCAL_ROOT.mkdir(parents=True, exist_ok=True)
print("CPU preparation environment is ready.")

Mounted at /content/drive
CPU preparation environment is ready.

## 2. Run synthetic transformation checks

In [2]:
test_environment = dict(os.environ)
test_environment["PYTHONPATH"] = str(PROJECT_ROOT / "code/python")
subprocess.run(
    [sys.executable, "-m", "unittest", "discover",
     "-s", str(PROJECT_ROOT / "code/python/tests"),
     "-p", "test_capture_prepare.py", "-v"],
    env=test_environment,
    cwd=PROJECT_ROOT,
    check=True,
)

CompletedProcess(args=['/usr/bin/python3', '-m', 'unittest', 'discover', '-s', '/content/temporalgnn-nids/code/python/tests', '-p', 'test_capture_prepare.py', '-v'], returncode=0)

## 3. Configure the preparation run

In [7]:
from datetime import datetime, timezone
import pandas as pd
from IPython.display import display
from utils.capture_data import load_manifest, selected_scenarios, sha256_file, write_json
from utils.capture_prepare import run_capture_preparation

MANIFEST_PATH = PROJECT_ROOT / "configs/capture_experiment_v1.yaml"
PACKET_SCHEMA_PATH = PROJECT_ROOT / "configs/capture_packet_schema_v1.yaml"
AUDIT_RUN_DIR = (
    DRIVE_ROOT / "runs" / "20260917T170658_227477Z_full_dev"
)
DECISION_AUDIT_PATH = AUDIT_RUN_DIR / "gate0_decision_audit.json"

#MODE = "SMOKE"
MODE = "FULL_DEV"
PREPARATION_SMOKE_REVIEW_PATH = (
    "/content/drive/MyDrive/capture_gate0/prepared_runs/"
    "20260917T233015_342509Z_prepare_smoke/preparation_smoke_review.json"
)
BATCH_SIZE = 100_000

MANIFEST = load_manifest(MANIFEST_PATH)
SCENARIOS = selected_scenarios(MANIFEST, MODE)
RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S_%fZ") + "_prepare_" + MODE.lower()
DRIVE_RUN_DIR = DRIVE_ROOT / "prepared_runs" / RUN_ID

print(f"Mode: {MODE}")
print(f"Scenarios: {SCENARIOS}")
print(f"Source audit: {AUDIT_RUN_DIR}")
print(f"Output directory: {DRIVE_RUN_DIR}")
print(f"Free local storage: {shutil.disk_usage(LOCAL_ROOT).free / 1024**3:.1f} GiB")

Mode: FULL_DEV
Scenarios: ['train_empty_conn', 'train_qos_mid', 'train_dollar_char', 'train_slash_char', 'train_sub_exf']
Source audit: /content/drive/MyDrive/capture_gate0/runs/20260917T170658_227477Z_full_dev
Output directory: /content/drive/MyDrive/capture_gate0/prepared_runs/20260917T235058_827743Z_prepare_full_dev
Free local storage: 85.2 GiB

## 4. Prepare and persist the selected scenarios

The input audit Parquet files remain on Drive. Each output is built in temporary local storage, copied to a fresh Drive run directory, checksum-verified, and then removed locally.

In [8]:
RESULTS = run_capture_preparation(
    manifest_path=MANIFEST_PATH,
    packet_schema_path=PACKET_SCHEMA_PATH,
    audit_run_dir=AUDIT_RUN_DIR,
    decision_audit_path=DECISION_AUDIT_PATH,
    mode=MODE,
    local_root=LOCAL_ROOT,
    drive_run_dir=DRIVE_RUN_DIR,
    smoke_review_path=(
        Path(PREPARATION_SMOKE_REVIEW_PATH)
        if PREPARATION_SMOKE_REVIEW_PATH is not None else None
    ),
    batch_size=BATCH_SIZE,
)
display(pd.DataFrame([
    {"scenario": scenario, **item}
    for scenario, item in RESULTS.items()
]))

Preparing train_empty_conn. Local workspace: /content/capture_prepare_work/train_empty_conn_fa1bihqc
train_empty_conn: prepared 100,000 packets
train_empty_conn: prepared 200,000 packets
train_empty_conn: prepared 300,000 packets
train_empty_conn: prepared 400,000 packets
train_empty_conn: prepared 500,000 packets
train_empty_conn: prepared 600,000 packets
train_empty_conn: prepared 700,000 packets
train_empty_conn: prepared 800,000 packets
train_empty_conn: prepared 900,000 packets
train_empty_conn: prepared 1,000,000 packets
train_empty_conn: prepared 1,100,000 packets
train_empty_conn: prepared 1,175,779 packets
Saved and verified train_empty_conn on Drive. Removed its local copy.
Preparing train_qos_mid. Local workspace: /content/capture_prepare_work/train_qos_mid_krumhk73
train_qos_mid: prepared 100,000 packets
train_qos_mid: prepared 200,000 packets
train_qos_mid: prepared 300,000 packets
train_qos_mid: prepared 400,000 packets
train_qos_mid: prepared 500,000 packets
train_qos_mid: prepared 600,000 packets
train_qos_mid: prepared 700,000 packets
train_qos_mid: prepared 800,000 packets
train_qos_mid: prepared 900,000 packets
train_qos_mid: prepared 1,000,000 packets
train_qos_mid: prepared 1,100,000 packets
train_qos_mid: prepared 1,200,000 packets
train_qos_mid: prepared 1,300,000 packets
train_qos_mid: prepared 1,400,000 packets
train_qos_mid: prepared 1,499,717 packets
Saved and verified train_qos_mid on Drive. Removed its local copy.
Preparing train_dollar_char. Local workspace: /content/capture_prepare_work/train_dollar_char_icfs6gk4
train_dollar_char: prepared 100,000 packets
train_dollar_char: prepared 200,000 packets
train_dollar_char: prepared 300,000 packets
train_dollar_char: prepared 400,000 packets
train_dollar_char: prepared 500,000 packets
train_dollar_char: prepared 600,000 packets
train_dollar_char: prepared 700,000 packets
train_dollar_char: prepared 800,000 packets
train_dollar_char: prepared 900,000 packets
train_dollar_char: prepared 1,000,000 packets
train_dollar_char: prepared 1,100,000 packets
train_dollar_char: prepared 1,200,000 packets
train_dollar_char: prepared 1,300,000 packets
train_dollar_char: prepared 1,400,000 packets
train_dollar_char: prepared 1,500,000 packets
train_dollar_char: prepared 1,600,000 packets
train_dollar_char: prepared 1,700,000 packets
train_dollar_char: prepared 1,800,000 packets
train_dollar_char: prepared 1,900,000 packets
train_dollar_char: prepared 2,000,000 packets
train_dollar_char: prepared 2,100,000 packets
train_dollar_char: prepared 2,200,000 packets
train_dollar_char: prepared 2,300,000 packets
train_dollar_char: prepared 2,400,000 packets
train_dollar_char: prepared 2,500,000 packets
train_dollar_char: prepared 2,600,000 packets
train_dollar_char: prepared 2,700,000 packets
train_dollar_char: prepared 2,800,000 packets
train_dollar_char: prepared 2,882,555 packets
Saved and verified train_dollar_char on Drive. Removed its local copy.
Preparing train_slash_char. Local workspace: /content/capture_prepare_work/train_slash_char_q9c775fm
train_slash_char: prepared 100,000 packets
train_slash_char: prepared 200,000 packets
train_slash_char: prepared 300,000 packets
train_slash_char: prepared 400,000 packets
train_slash_char: prepared 500,000 packets
train_slash_char: prepared 600,000 packets
train_slash_char: prepared 700,000 packets
train_slash_char: prepared 800,000 packets
train_slash_char: prepared 900,000 packets
train_slash_char: prepared 1,000,000 packets
train_slash_char: prepared 1,100,000 packets
train_slash_char: prepared 1,200,000 packets
train_slash_char: prepared 1,300,000 packets
train_slash_char: prepared 1,400,000 packets
train_slash_char: prepared 1,500,000 packets
train_slash_char: prepared 1,600,000 packets
train_slash_char: prepared 1,700,000 packets
train_slash_char: prepared 1,800,000 packets
train_slash_char: prepared 1,900,000 packets
train_slash_char: prepared 2,000,000 packets
train_slash_char: prepared 2,100,000 packets
train_slash_char: prepared 2,200,000 packets
train_slash_char: prepared 2,300,000 packets
train_slash_char: prepared 2,400,000 packets
train_slash_char: prepared 2,500,000 packets
train_slash_char: prepared 2,600,000 packets
train_slash_char: prepared 2,700,000 packets
train_slash_char: prepared 2,800,000 packets
train_slash_char: prepared 2,900,000 packets
train_slash_char: prepared 3,000,000 packets
train_slash_char: prepared 3,100,000 packets
train_slash_char: prepared 3,200,000 packets
train_slash_char: prepared 3,300,000 packets
train_slash_char: prepared 3,400,000 packets
train_slash_char: prepared 3,500,000 packets
train_slash_char: prepared 3,600,000 packets
train_slash_char: prepared 3,700,000 packets
train_slash_char: prepared 3,800,000 packets
train_slash_char: prepared 3,900,000 packets
train_slash_char: prepared 4,000,000 packets
train_slash_char: prepared 4,100,000 packets
train_slash_char: prepared 4,200,000 packets
train_slash_char: prepared 4,300,000 packets
train_slash_char: prepared 4,400,000 packets
train_slash_char: prepared 4,500,000 packets
train_slash_char: prepared 4,600,000 packets
train_slash_char: prepared 4,700,000 packets
train_slash_char: prepared 4,800,000 packets
train_slash_char: prepared 4,900,000 packets
train_slash_char: prepared 5,000,000 packets
train_slash_char: prepared 5,100,000 packets
train_slash_char: prepared 5,200,000 packets
train_slash_char: prepared 5,300,000 packets
train_slash_char: prepared 5,400,000 packets
train_slash_char: prepared 5,500,000 packets
train_slash_char: prepared 5,600,000 packets
train_slash_char: prepared 5,700,000 packets
train_slash_char: prepared 5,800,000 packets
train_slash_char: prepared 5,900,000 packets
train_slash_char: prepared 6,000,000 packets
train_slash_char: prepared 6,100,000 packets
train_slash_char: prepared 6,200,000 packets
train_slash_char: prepared 6,300,000 packets
train_slash_char: prepared 6,400,000 packets
train_slash_char: prepared 6,425,516 packets
Saved and verified train_slash_char on Drive. Removed its local copy.
Preparing train_sub_exf. Local workspace: /content/capture_prepare_work/train_sub_exf_zcpbeu_a
train_sub_exf: prepared 100,000 packets
train_sub_exf: prepared 200,000 packets
train_sub_exf: prepared 300,000 packets
train_sub_exf: prepared 400,000 packets
train_sub_exf: prepared 500,000 packets
train_sub_exf: prepared 600,000 packets
train_sub_exf: prepared 700,000 packets
train_sub_exf: prepared 800,000 packets
train_sub_exf: prepared 900,000 packets
train_sub_exf: prepared 1,000,000 packets
train_sub_exf: prepared 1,100,000 packets
train_sub_exf: prepared 1,200,000 packets
train_sub_exf: prepared 1,300,000 packets
train_sub_exf: prepared 1,400,000 packets
train_sub_exf: prepared 1,500,000 packets
train_sub_exf: prepared 1,600,000 packets
train_sub_exf: prepared 1,700,000 packets
train_sub_exf: prepared 1,800,000 packets
train_sub_exf: prepared 1,900,000 packets
train_sub_exf: prepared 2,000,000 packets
train_sub_exf: prepared 2,100,000 packets
train_sub_exf: prepared 2,200,000 packets
train_sub_exf: prepared 2,225,807 packets
Saved and verified train_sub_exf on Drive. Removed its local copy.

,scenario,status,report
0,train_empty_conn,review_required,/content/drive/MyDrive/capture_gate0/prepared_...
1,train_qos_mid,review_required,/content/drive/MyDrive/capture_gate0/prepared_...
2,train_dollar_char,review_required,/content/drive/MyDrive/capture_gate0/prepared_...
3,train_slash_char,review_required,/content/drive/MyDrive/capture_gate0/prepared_...
4,train_sub_exf,review_required,/content/drive/MyDrive/capture_gate0/prepared_...

## 5. Review the preparation reports

In [9]:
REPORTS = {}
summary_rows = []
role_rows = []
null_rows = []

for scenario in SCENARIOS:
    report_path = DRIVE_RUN_DIR / scenario / "preparation_report.json"
    report = json.loads(report_path.read_text())
    REPORTS[scenario] = report
    summary_rows.append({
        "scenario": scenario,
        **report["counts"],
        "output_gib": report["output_size_bytes"] / 1024**3,
        "features": len(report["feature_columns"]),
        "origin_timestamp_ns": report["scenario_origin_timestamp_ns"],
        "last_timestamp_ns": report["last_packet_timestamp_ns"],
        "duration_seconds": report["duration_seconds"],
    })
    role_rows.append({"scenario": scenario, **report["destination_node_role_counts"]})
    for feature, missing in report["feature_null_counts"].items():
        null_rows.append({
            "scenario": scenario, "feature": feature, "null_values": missing,
            "null_fraction": missing / report["counts"]["packets"],
        })

print("Scenario summary")
display(pd.DataFrame(summary_rows))
print("Destination node roles")
display(pd.DataFrame(role_rows))
print("Feature null fractions")
null_frame = pd.DataFrame(null_rows)
for scenario in SCENARIOS:
    print(scenario)
    display(
        null_frame[null_frame["scenario"] == scenario]
        .drop(columns="scenario")
        .reset_index(drop=True)
    )

Scenario summary

,scenario,packets,normal_packets,attack_packets,output_gib,features,origin_timestamp_ns,last_timestamp_ns,duration_seconds
0,train_empty_conn,1175779,746806,428973,0.061369,42,19792000,46799813163000,46799.793371
1,train_qos_mid,1499717,746806,752911,0.078339,42,19792000,46799813163000,46799.793371
2,train_dollar_char,2882555,1705003,1177552,0.148095,42,9927000,46796778032000,46796.768105
3,train_slash_char,6425516,1705003,4720513,0.315006,42,9927000,46796778032000,46796.768105
4,train_sub_exf,2225807,1705003,520804,0.112849,42,9927000,46796778032000,46796.768105

Destination node roles

            scenario  broadcast  multicast  unicast
0   train_empty_conn      19805      27000  1128974
1      train_qos_mid      20980      26240  1452497
2  train_dollar_char      26334      23599  2832622
3   train_slash_char      53481      22114  6349921
4      train_sub_exf      94429      22280  2109098

Feature null fractions
train_empty_conn

                     feature  null_values  null_fraction
0   destination_is_broadcast            0       0.000000
1   destination_is_multicast            0       0.000000
2              ethernet_type            0       0.000000
3               frame_length            0       0.000000
4                  ipv4_dscp        76267       0.064865
5               ipv4_flag_df        76267       0.064865
6               ipv4_flag_mf        76267       0.064865
7       ipv4_fragment_offset        76267       0.064865
8                ipv4_length        76267       0.064865
9                   ipv4_ttl        76267       0.064865
10        ipv6_fragment_more      1151491       0.979343
11                    is_arp            0       0.000000
12                   is_ipv4            0       0.000000
13                   is_ipv6            0       0.000000
14              is_malformed            0       0.000000
15                   is_mqtt            0       0.000000
16                    is_ssh            0       0.000000
17                    is_tcp            0       0.000000
18                    is_udp            0       0.000000
19  mqtt_connack_reason_code      1175778       0.999999
20       mqtt_duplicate_flag      1004309       0.854165
21         mqtt_message_type       692973       0.589374
22                  mqtt_qos      1004309       0.854165
23        mqtt_reserved_flag       864443       0.735209
24          mqtt_retain_flag      1004309       0.854165
25     mqtt_subscription_qos      1175772       0.999994
26              mqtt_version      1175651       0.999891
27             ssh_direction      1070479       0.910442
28        ssh_padding_length      1169207       0.994411
29      tcp_destination_port        77443       0.065865
30              tcp_flag_ack        77443       0.065865
31              tcp_flag_cwr        77443       0.065865
32              tcp_flag_ece        77443       0.065865
33              tcp_flag_fin        77443       0.065865
34              tcp_flag_psh        77443       0.065865
35              tcp_flag_rst        77443       0.065865
36              tcp_flag_syn        77443       0.065865
37              tcp_flag_urg        77443       0.065865
38         tcp_header_length        77443       0.065865
39        tcp_payload_length        77443       0.065865
40           tcp_source_port        77443       0.065865
41          tcp_window_value        77443       0.065865

train_qos_mid

                     feature  null_values  null_fraction
0   destination_is_broadcast            0       0.000000
1   destination_is_multicast            0       0.000000
2              ethernet_type            0       0.000000
3               frame_length            0       0.000000
4                  ipv4_dscp        73261       0.048850
5               ipv4_flag_df        73261       0.048850
6               ipv4_flag_mf        73261       0.048850
7       ipv4_fragment_offset        73261       0.048850
8                ipv4_length        73261       0.048850
9                   ipv4_ttl        73261       0.048850
10        ipv6_fragment_more      1476097       0.984250
11                    is_arp            0       0.000000
12                   is_ipv4            0       0.000000
13                   is_ipv6            0       0.000000
14              is_malformed            0       0.000000
15                   is_mqtt            0       0.000000
16                    is_ssh            0       0.000000
17                    is_tcp            0       0.000000
18                    is_udp            0       0.000000
19  mqtt_connack_reason_code      1499715       0.999999
20       mqtt_duplicate_flag      1309758       0.873337
21         mqtt_message_type       962659       0.641894
22                  mqtt_qos      1309758       0.873337
23        mqtt_reserved_flag      1152618       0.768557
24          mqtt_retain_flag      1309758       0.873337
25     mqtt_subscription_qos      1499701       0.999989
26              mqtt_version      1481196       0.987650
27             ssh_direction      1428249       0.952346
28        ssh_padding_length      1494557       0.996559
29      tcp_destination_port        74017       0.049354
30              tcp_flag_ack        74017       0.049354
31              tcp_flag_cwr        74017       0.049354
32              tcp_flag_ece        74017       0.049354
33              tcp_flag_fin        74017       0.049354
34              tcp_flag_psh        74017       0.049354
35              tcp_flag_rst        74017       0.049354
36              tcp_flag_syn        74017       0.049354
37              tcp_flag_urg        74017       0.049354
38         tcp_header_length        74017       0.049354
39        tcp_payload_length        74017       0.049354
40           tcp_source_port        74017       0.049354
41          tcp_window_value        74017       0.049354

train_dollar_char

                     feature  null_values  null_fraction
0   destination_is_broadcast            0       0.000000
1   destination_is_multicast            0       0.000000
2              ethernet_type            0       0.000000
3               frame_length            0       0.000000
4                  ipv4_dscp        81195       0.028168
5               ipv4_flag_df        81195       0.028168
6               ipv4_flag_mf        81195       0.028168
7       ipv4_fragment_offset        81195       0.028168
8                ipv4_length        81195       0.028168
9                   ipv4_ttl        81195       0.028168
10        ipv6_fragment_more      2861429       0.992671
11                    is_arp            0       0.000000
12                   is_ipv4            0       0.000000
13                   is_ipv6            0       0.000000
14              is_malformed            0       0.000000
15                   is_mqtt            0       0.000000
16                    is_ssh            0       0.000000
17                    is_tcp            0       0.000000
18                    is_udp            0       0.000000
19  mqtt_connack_reason_code      2882553       0.999999
20       mqtt_duplicate_flag      2333486       0.809520
21         mqtt_message_type      1392721       0.483155
22                  mqtt_qos      2333486       0.809520
23        mqtt_reserved_flag      1941790       0.673635
24          mqtt_retain_flag      2333486       0.809520
25     mqtt_subscription_qos      2882540       0.999995
26              mqtt_version      2882364       0.999934
27             ssh_direction      2659683       0.922682
28        ssh_padding_length      2879775       0.999036
29      tcp_destination_port        82371       0.028576
30              tcp_flag_ack        82371       0.028576
31              tcp_flag_cwr        82371       0.028576
32              tcp_flag_ece        82371       0.028576
33              tcp_flag_fin        82371       0.028576
34              tcp_flag_psh        82371       0.028576
35              tcp_flag_rst        82371       0.028576
36              tcp_flag_syn        82371       0.028576
37              tcp_flag_urg        82371       0.028576
38         tcp_header_length        82371       0.028576
39        tcp_payload_length        82371       0.028576
40           tcp_source_port        82371       0.028576
41          tcp_window_value        82371       0.028576

train_slash_char

                     feature  null_values  null_fraction
0   destination_is_broadcast            0       0.000000
1   destination_is_multicast            0       0.000000
2              ethernet_type            0       0.000000
3               frame_length            0       0.000000
4                  ipv4_dscp       104666       0.016289
5               ipv4_flag_df       104666       0.016289
6               ipv4_flag_mf       104666       0.016289
7       ipv4_fragment_offset       104666       0.016289
8                ipv4_length       104666       0.016289
9                   ipv4_ttl       104666       0.016289
10        ipv6_fragment_more      6405796       0.996931
11                    is_arp            0       0.000000
12                   is_ipv4            0       0.000000
13                   is_ipv6            0       0.000000
14              is_malformed            0       0.000000
15                   is_mqtt            0       0.000000
16                    is_ssh            0       0.000000
17                    is_tcp            0       0.000000
18                    is_udp            0       0.000000
19  mqtt_connack_reason_code      6425408       0.999983
20       mqtt_duplicate_flag      6057498       0.942726
21         mqtt_message_type      5103958       0.794327
22                  mqtt_qos      6057498       0.942726
23        mqtt_reserved_flag      5471976       0.851601
24          mqtt_retain_flag      6057498       0.942726
25     mqtt_subscription_qos      6420981       0.999294
26              mqtt_version      6420946       0.999289
27             ssh_direction      6322776       0.984011
28        ssh_padding_length      6418628       0.998928
29      tcp_destination_port       104918       0.016328
30              tcp_flag_ack       104918       0.016328
31              tcp_flag_cwr       104918       0.016328
32              tcp_flag_ece       104918       0.016328
33              tcp_flag_fin       104918       0.016328
34              tcp_flag_psh       104918       0.016328
35              tcp_flag_rst       104918       0.016328
36              tcp_flag_syn       104918       0.016328
37              tcp_flag_urg       104918       0.016328
38         tcp_header_length       104918       0.016328
39        tcp_payload_length       104918       0.016328
40           tcp_source_port       104918       0.016328
41          tcp_window_value       104918       0.016328

train_sub_exf

                     feature  null_values  null_fraction
0   destination_is_broadcast            0       0.000000
1   destination_is_multicast            0       0.000000
2              ethernet_type            0       0.000000
3               frame_length            0       0.000000
4                  ipv4_dscp       154962       0.069621
5               ipv4_flag_df       154962       0.069621
6               ipv4_flag_mf       154962       0.069621
7       ipv4_fragment_offset       154962       0.069621
8                ipv4_length       154962       0.069621
9                   ipv4_ttl       154962       0.069621
10        ipv6_fragment_more      2205947       0.991077
11                    is_arp            0       0.000000
12                   is_ipv4            0       0.000000
13                   is_ipv6            0       0.000000
14              is_malformed            0       0.000000
15                   is_mqtt            0       0.000000
16                    is_ssh            0       0.000000
17                    is_tcp            0       0.000000
18                    is_udp            0       0.000000
19  mqtt_connack_reason_code      2225803       0.999998
20       mqtt_duplicate_flag      1857790       0.834659
21         mqtt_message_type       917412       0.412171
22                  mqtt_qos      1857790       0.834659
23        mqtt_reserved_flag      1285429       0.577511
24          mqtt_retain_flag      1857790       0.834659
25     mqtt_subscription_qos      2225706       0.999955
26              mqtt_version      2225696       0.999950
27             ssh_direction      2121220       0.953012
28        ssh_padding_length      2218639       0.996780
29      tcp_destination_port       162354       0.072942
30              tcp_flag_ack       162354       0.072942
31              tcp_flag_cwr       162354       0.072942
32              tcp_flag_ece       162354       0.072942
33              tcp_flag_fin       162354       0.072942
34              tcp_flag_psh       162354       0.072942
35              tcp_flag_rst       162354       0.072942
36              tcp_flag_syn       162354       0.072942
37              tcp_flag_urg       162354       0.072942
38         tcp_header_length       162354       0.072942
39        tcp_payload_length       162354       0.072942
40           tcp_source_port       162354       0.072942
41          tcp_window_value       162354       0.072942

## 6. Record the preparation SMOKE review

Set `APPROVE_PREPARATION_SMOKE` to `True` only after reviewing Section 5. The resulting JSON authorizes `FULL_DEV` for this exact manifest, packet schema, and pair of SMOKE reports.

In [6]:
APPROVE_PREPARATION_SMOKE = True
PREPARATION_REVIEW_NOTES = (
    "Canonical packet counts, timestamp ranges, parsed features, node roles, "
    "and null fractions were reviewed without blockers."
)

if MODE != "SMOKE":
    print("This section applies only to a SMOKE preparation run.")
elif APPROVE_PREPARATION_SMOKE:
    review = {
        "approved": True,
        "manifest_sha256": sha256_file(MANIFEST_PATH),
        "packet_schema_sha256": sha256_file(PACKET_SCHEMA_PATH),
        "review_notes": PREPARATION_REVIEW_NOTES,
        "reports": {},
    }
    for scenario in SCENARIOS:
        report_path = DRIVE_RUN_DIR / scenario / "preparation_report.json"
        review["reports"][scenario] = {
            "path": str(report_path),
            "sha256": sha256_file(report_path),
        }
    review_path = DRIVE_RUN_DIR / "preparation_smoke_review.json"
    write_json(review_path, review)
    print(f"Preparation SMOKE approved: {review_path}")
else:
    print("Preparation SMOKE review remains pending. No approval was recorded.")

Preparation SMOKE approved: /content/drive/MyDrive/capture_gate0/prepared_runs/20260917T233015_342509Z_prepare_smoke/preparation_smoke_review.json