# cAPTure: Gate-0 data audit

Run this notebook in Google Colab with a **CPU runtime**. It audits development scenarios before selecting features, graph endpoints, or a window duration. It does not train models or access final-test scenarios.

The workflow uses the authors' public Drive for source CSVs and your mounted Drive for durable results, and local Colab disk for conversion and SQL aggregation. Process one scenario at a time. Start with `SMOKE`; `FULL_DEV` requires a reviewed smoke run.

The audit Parquet preserves every source row and raw column alongside diagnostic metadata. It is **not** a frozen, model-ready canonical dataset. No features are selected, labels guessed, or duplicate packets removed.

## 1. Mount Drive and load the project

Before running, push the implementation to the configured Git branch, or place an updated repository copy in Drive and set `PROJECT_ROOT` to that path. This notebook imports the repository module; it is not self-contained.

The manifest contains verified development CSV IDs, filenames, and byte sizes from the authors' [pre-merged training scenario folder](https://drive.google.com/drive/folders/1f8koJbuPs0_CWoItWdt3VF-lZ_R6JAms). No raw CSV copies are needed in your Drive. Colab downloads individual files by ID; it never recursively downloads the folder.

Folder metadata verification does not prove packet-level integrity. That is the purpose of Gate 0.

In [1]:
from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path
import os
import subprocess
import sys

REPOSITORY_URL = "https://github.com/tatipar/temporalgnn-nids.git"
REPOSITORY_BRANCH = "feat/capture-feasibility"
PROJECT_ROOT = Path("/content/temporalgnn-nids")
DRIVE_ROOT = Path("/content/drive/MyDrive/capture_gate0")
LOCAL_ROOT = Path("/content/capture_gate0_work")

if not PROJECT_ROOT.exists():
    subprocess.run(
        ["git", "clone", "--branch", REPOSITORY_BRANCH, "--single-branch",
         REPOSITORY_URL, str(PROJECT_ROOT)], check=True
    )

required_files = [
    PROJECT_ROOT / "code/python/utils/capture_data.py",
    PROJECT_ROOT / "code/python/requirements-capture.txt",
    PROJECT_ROOT / "configs/capture_experiment_v1.yaml",
]
missing_files = [str(path) for path in required_files if not path.exists()]
if missing_files:
    raise FileNotFoundError(f"Update the repository copy first: {missing_files}")

subprocess.run(
    [sys.executable, "-m", "pip", "install", "-q", "-r",
     str(PROJECT_ROOT / "code/python/requirements-capture.txt")], check=True
)
sys.path.insert(0, str(PROJECT_ROOT / "code/python"))
DRIVE_ROOT.mkdir(parents=True, exist_ok=True)
LOCAL_ROOT.mkdir(parents=True, exist_ok=True)
print("CPU audit environment is ready.")

Mounted at /content/drive
CPU audit environment is ready.

## 2. Run the small synthetic checks

Run these checks before downloading or processing large files. They cover half-open windows, repeated packets, cross-chunk timestamp inversions, unknown labels, held-out exclusion, and smoke-review integrity. They use temporary synthetic data and do not inspect cAPTure contents.

These checks have not been executed in the development workspace; this Colab run is the first runtime validation.

In [2]:
test_environment = dict(os.environ)
test_environment["PYTHONPATH"] = str(PROJECT_ROOT / "code/python")
subprocess.run(
    [sys.executable, "-m", "unittest", "discover",
     "-s", str(PROJECT_ROOT / "code/python/tests"),
     "-p", "test_capture_data.py", "-v"],
    env=test_environment, cwd=PROJECT_ROOT, check=True,
)

CompletedProcess(args=['/usr/bin/python3', '-m', 'unittest', 'discover', '-s', '/content/temporalgnn-nids/code/python/tests', '-p', 'test_capture_data.py', '-v'], returncode=0)

## 3. Configure the audit and official downloads

Start with `SMOKE` (`train_empty_conn` and `train_dollar_char`). The source configuration is built from the manifest. Only development author-train scenarios are permitted. Your Drive stores reports and compressed audit Parquet; raw CSVs are staged on local Colab disk.

For `FULL_DEV`, supply a smoke-review file from section 8. A unique run directory prevents overwriting earlier results. Leave the chunk size at 25,000 initially; reduce it if wide CSV columns exhaust RAM. DuckDB is limited to two threads and 2 GB, but pandas and Arrow also need memory.

Google Drive may temporarily impose download quotas. If a download fails, the error is preserved; no alternative dataset is substituted.

In [3]:
from datetime import datetime, timezone
import json
import shutil
import pandas as pd
from IPython.display import display
from utils.capture_data import (
    AuditSchema, inspect_csv, load_manifest, run_gate0, selected_scenarios, stage_source,
    sha256_file, validate_smoke_review, write_json,
)

MANIFEST_PATH = PROJECT_ROOT / "configs/capture_experiment_v1.yaml"
MANIFEST = load_manifest(MANIFEST_PATH)
#MODE = "SMOKE"
MODE = "FULL_DEV"
SCENARIOS = selected_scenarios(MANIFEST, MODE)
RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S_%fZ") + "_" + MODE.lower()
DRIVE_RUN_DIR = DRIVE_ROOT / "runs" / RUN_ID

CHUNK_SIZE = 25_000
DUCKDB_MEMORY_LIMIT = "2GB"
DUCKDB_THREADS = 2
KEEP_AUDIT_PARQUET = True
#SMOKE_REVIEW_PATH = None  # Set the reviewed smoke JSON path before FULL_DEV.
SMOKE_REVIEW_PATH = "/content/drive/MyDrive/capture_gate0/runs/20260917T155516_689141Z_smoke/smoke_review.json"


SOURCE_CACHE_ROOT = LOCAL_ROOT / RUN_ID / "sources"
SOURCES = {}
for scenario in SCENARIOS:
    entry = MANIFEST["scenarios"][scenario]
    required = ("source_file_id", "expected_filename", "expected_size_bytes")
    if any(entry.get(key) is None for key in required):
        raise ValueError(f"Source metadata is incomplete for {scenario}. Update the manifest.")
    SOURCES[scenario] = {
        **{key: entry[key] for key in required},
        "metadata_verified": True,
    }

if MODE == "FULL_DEV":
    if SMOKE_REVIEW_PATH is None:
        raise ValueError("Set SMOKE_REVIEW_PATH before inspecting FULL_DEV sources.")
    validate_smoke_review(Path(SMOKE_REVIEW_PATH), sha256_file(MANIFEST_PATH), MANIFEST)

print(f"Mode: {MODE}")
print(f"Scenarios: {SCENARIOS}")
print(f"Output directory: {DRIVE_RUN_DIR}")
print(f"Free local storage: {shutil.disk_usage(LOCAL_ROOT).free / 1024**3:.1f} GiB")

Mode: FULL_DEV
Scenarios: ['train_empty_conn', 'train_qos_mid', 'train_dollar_char', 'train_slash_char', 'train_sub_exf']
Output directory: /content/drive/MyDrive/capture_gate0/runs/20260917T201026_302809Z_full_dev
Free local storage: 87.3 GiB

## 4. Download and inspect the first scenario

Download the first selected CSV to local Colab disk, then read a prefix of 2,000 rows. The completed download is bound to its source configuration and a local SHA-256 receipt. The audit reuses it after verifying the receipt, so it is not downloaded twice.

Only one scenario is staged for preview. Remaining schemas are checked against their CSV headers when each scenario is processed. Missing attack labels in the preview do not mean the full scenario contains no attacks.

All raw columns are initially read as strings to preserve identifiers, leading zeros, empty fields, and mixed types. The preview is not used to fit preprocessing or select features.

In [ ]:
CSV_SEPARATOR = ","
CSV_ENCODING = "utf-8-sig"
for source in SOURCES.values():
    source["separator"] = CSV_SEPARATOR
    source["encoding"] = CSV_ENCODING

PREVIEW_SCENARIO = SCENARIOS[0]
preview_path = stage_source(
    SOURCES[PREVIEW_SCENARIO], SOURCE_CACHE_ROOT / PREVIEW_SCENARIO,
)
inspection = inspect_csv(
    preview_path, separator=CSV_SEPARATOR,
    encoding=CSV_ENCODING, sample_rows=2_000,
)
INSPECTIONS = {PREVIEW_SCENARIO: inspection}
print(f"{PREVIEW_SCENARIO}: {inspection['source_size_bytes'] / 1024**3:.2f} GiB")
display(pd.DataFrame([
    {"column": column, "prefix_examples": values}
    for column, values in inspection["sample_values"].items()
]))

Downloading...
From (original): https://drive.google.com/uc?id=1nfR1RRZO3jMG_A9KDY8wyr0A0rVlHiBN
From (redirected): https://drive.google.com/uc?id=1nfR1RRZO3jMG_A9KDY8wyr0A0rVlHiBN&confirm=t&uuid=fd7fd1ef-76a1-435d-a747-49107894472b
To: /content/capture_gate0_work/20260917T170658_227477Z_full_dev/sources/train_empty_conn/normal_empty_conn_train.csv.part
100%|██████████| 1.03G/1.03G [00:28<00:00, 36.7MB/s]

train_empty_conn: 0.96 GiB

,column,prefix_examples
0,layers_frame_frame.section_number,[1]
1,timestamp,"[1970-01-01 01:00:00.019792+01:00, 1970-01-01 ..."
2,layers_frame_frame.time_epoch,"[0.019792, 0.036245, 0.03809, 0.051729, 0.0682..."
3,layers_frame_frame.number,"[1, 2, 3, 4, 5, 6, 7, 8]"
4,layers_frame_frame.len,"[114, 90, 111, 64, 78, 70, 100, 74]"
...,...,...
103,phase_idx,[]
104,phase_name,[]
105,phase_number,[]
106,step_number,[]
107,sequence_id,[]

## 5. Confirm the declared schema

The mapping below follows the authors' scenario-construction notebooks:

- `timestamp` is the post-merge timestamp. The relative frame epoch is not used because the merge adjusts `timestamp`.
- `label` contains `normal` or the attack command. It is also the most specific published attack-step name.
- `phase_name` and `sequence_id` retain the authors' evaluation annotations.
- Ethernet source and destination MAC fields are provisional Gate-0 endpoints because they cover IP, IPv6, ARP, and other Ethernet traffic. Gate 0 will determine whether this remains the graph node key.

The raw-to-binary mappings enumerate the values reported by the official merge notebooks for all five development author-train scenarios. Any additional value remains unmapped and blocks progression. Endpoint identifiers are topology metadata and are not approved as model features.

The diagnostic iteration key is `(scenario, attack_step, phase, sequence_id)`. Its scientific meaning must still be reviewed after the audit.

In [ ]:
COMMON_SCHEMA = {
    "timestamp": "timestamp",
    "timestamp_unit": "datetime",
    "label": "label",
    "source_endpoint": "layers_eth_eth.src",
    "destination_endpoint": "layers_eth_eth.dst",
    "attack_step": "label",
    "phase": "phase_name",
    "sequence_id": "sequence_id",
    "separator": CSV_SEPARATOR,
    "encoding": CSV_ENCODING,
}
SCHEMA_OVERRIDES = {
    "train_empty_conn": {
        "label_mapping": {
            "normal": 0,
            "nmap_10_T4": 1,
            "brute_force_timing": 1,
            "empty_conn_ddos": 1,
            "nmap_mqtt": 1,
            "nmap_banner": 1,
            "empty_conn": 1,
            "nmap_sub": 1,
            "mqtt_cat": 1,
            "sftp_inst": 1,
        },
    },
    "train_dollar_char": {
        "label_mapping": {
            "normal": 0,
            "dollar_char": 1,
            "nmap_10_T5": 1,
            "nmap_mqtt": 1,
            "brute_force_malformed": 1,
            "nmap_banner": 1,
            "nmap_sub": 1,
            "mqtt_cat": 1,
            "scp_inst": 1,
        },
    },
    "train_qos_mid": {
        "label_mapping": {
            "normal": 0,
            "nmap_10_T5": 1,
            "qos_mid_ddos": 1,
            "brute_force_malformed": 1,
            "qos_mid": 1,
            "nmap_sub": 1,
            "nmap_mqtt": 1,
            "nmap_banner": 1,
            "mqtt_cat": 1,
            "scp_inst": 1,
        },
    },
    "train_slash_char": {
        "label_mapping": {
            "normal": 0,
            "nmap_10_T4": 1,
            "slash_char": 1,
            "nmap_10_T5": 1,
            "brute_force_timing": 1,
            "nmap_mqtt": 1,
            "nmap_banner": 1,
            "nmap_sub": 1,
            "mqtt_cat": 1,
            "sftp_inst": 1,
        },
    },
    "train_sub_exf": {
        "label_mapping": {
            "normal": 0,
            "nmap_10_T5": 1,
            "brute_force_timing": 1,
            "nmap_banner": 1,
            "nmap_sub": 1,
            "scp_exf": 1,
            "nmap_mqtt": 1,
            "mqtt_cat": 1,
        },
    },
}
SCHEMAS = {}
for scenario in SCENARIOS:
    settings = {**COMMON_SCHEMA, **SCHEMA_OVERRIDES.get(scenario, {})}
    unresolved = [key for key, value in settings.items() if value is None]
    if unresolved or not settings.get("label_mapping"):
        raise ValueError(f"Resolve schema fields for {scenario}: {unresolved}")
    schema = AuditSchema(**settings)
    if scenario in INSPECTIONS:
        schema.validate(INSPECTIONS[scenario]["columns"])
    SCHEMAS[scenario] = schema
print("All selected scenario mappings are explicit.")

All selected scenario mappings are explicit.

## 6. Run the complete scenario audit

This cell scans each selected CSV completely. It downloads or reuses one raw file locally, writes compressed audit Parquet, and computes disk-backed statistics for 1, 5, 10, and 30 seconds, including half-window origin shifts. Epoch-aligned boundaries are diagnostic candidates, not a frozen window choice.

Repeated packets remain distinct rows. Duplicate-row and duplicate-column detection uses SHA-256 fingerprints. Numeric parse failures may indicate legitimate categorical fields; inspect them before declaring malformed data. Window distributions describe occupied windows; empty windows between the first and last packet are counted separately.

Report files are copied to Drive and checksum-verified. Only then is that scenario's isolated local workspace deleted. The authors' originals are never modified. The preview download is reused and removed only after its results are safely persisted. A failure retains local work and records its location on Drive; a data-integrity blocker stops before the next scenario. SQL spill space can exceed raw size, so monitor local storage.

An audit with no automatic blockers still requires review of endpoints, sequence semantics, timestamps, duplicates, feature leakage, and window feasibility.

In [ ]:
RESULTS = run_gate0(
    manifest_path=MANIFEST_PATH,
    mode=MODE,
    sources=SOURCES,
    schemas=SCHEMAS,
    local_root=LOCAL_ROOT,
    drive_run_dir=DRIVE_RUN_DIR,
    smoke_review_path=Path(SMOKE_REVIEW_PATH) if SMOKE_REVIEW_PATH else None,
    chunksize=CHUNK_SIZE,
    memory_limit=DUCKDB_MEMORY_LIMIT,
    threads=DUCKDB_THREADS,
    keep_audit_parquet=KEEP_AUDIT_PARQUET,
    source_cache_root=SOURCE_CACHE_ROOT,
)
print(json.dumps(RESULTS, indent=2))

Starting train_empty_conn. Local workspace: /content/capture_gate0_work/train_empty_conn_zk6tz9ox
Reusing verified local source: normal_empty_conn_train.csv
train_empty_conn: converted 25,000 packets
train_empty_conn: converted 50,000 packets
train_empty_conn: converted 75,000 packets
train_empty_conn: converted 100,000 packets
train_empty_conn: converted 125,000 packets
train_empty_conn: converted 150,000 packets
train_empty_conn: converted 175,000 packets
train_empty_conn: converted 200,000 packets
train_empty_conn: converted 225,000 packets
train_empty_conn: converted 250,000 packets
train_empty_conn: converted 275,000 packets
train_empty_conn: converted 300,000 packets
train_empty_conn: converted 325,000 packets
train_empty_conn: converted 350,000 packets
train_empty_conn: converted 375,000 packets
train_empty_conn: converted 400,000 packets
train_empty_conn: converted 425,000 packets
train_empty_conn: converted 450,000 packets
train_empty_conn: converted 475,000 packets
train_empty_conn: converted 500,000 packets
train_empty_conn: converted 525,000 packets
train_empty_conn: converted 550,000 packets
train_empty_conn: converted 575,000 packets
train_empty_conn: converted 600,000 packets
train_empty_conn: converted 625,000 packets
train_empty_conn: converted 650,000 packets
train_empty_conn: converted 675,000 packets
train_empty_conn: converted 700,000 packets
train_empty_conn: converted 725,000 packets
train_empty_conn: converted 750,000 packets
train_empty_conn: converted 775,000 packets
train_empty_conn: converted 800,000 packets
train_empty_conn: converted 825,000 packets
train_empty_conn: converted 850,000 packets
train_empty_conn: converted 875,000 packets
train_empty_conn: converted 900,000 packets
train_empty_conn: converted 925,000 packets
train_empty_conn: converted 950,000 packets
train_empty_conn: converted 975,000 packets
train_empty_conn: converted 1,000,000 packets
train_empty_conn: converted 1,025,000 packets
train_empty_conn: converted 1,050,000 packets
train_empty_conn: converted 1,075,000 packets
train_empty_conn: converted 1,100,000 packets
train_empty_conn: converted 1,125,000 packets
train_empty_conn: converted 1,150,000 packets
train_empty_conn: converted 1,175,000 packets
train_empty_conn: converted 1,175,779 packets
Saved and verified train_empty_conn on Drive. Removed its temporary local copy.
Starting train_qos_mid. Local workspace: /content/capture_gate0_work/train_qos_mid__k8ncvlh

Downloading...
From (original): https://drive.google.com/uc?id=1syQC83AZTi-J6VHW2g1p__vqKQorXq6l
From (redirected): https://drive.google.com/uc?id=1syQC83AZTi-J6VHW2g1p__vqKQorXq6l&confirm=t&uuid=17bd535e-371b-47db-a390-635975e48af3
To: /content/capture_gate0_work/20260917T170658_227477Z_full_dev/sources/train_qos_mid/normal_qos_mid_train.csv.part
100%|██████████| 1.04G/1.04G [00:35<00:00, 29.0MB/s]

train_qos_mid: converted 25,000 packets
train_qos_mid: converted 50,000 packets
train_qos_mid: converted 75,000 packets
train_qos_mid: converted 100,000 packets
train_qos_mid: converted 125,000 packets
train_qos_mid: converted 150,000 packets
train_qos_mid: converted 175,000 packets
train_qos_mid: converted 200,000 packets
train_qos_mid: converted 225,000 packets
train_qos_mid: converted 250,000 packets
train_qos_mid: converted 275,000 packets
train_qos_mid: converted 300,000 packets
train_qos_mid: converted 325,000 packets
train_qos_mid: converted 350,000 packets
train_qos_mid: converted 375,000 packets
train_qos_mid: converted 400,000 packets
train_qos_mid: converted 425,000 packets
train_qos_mid: converted 450,000 packets
train_qos_mid: converted 475,000 packets
train_qos_mid: converted 500,000 packets
train_qos_mid: converted 525,000 packets
train_qos_mid: converted 550,000 packets
train_qos_mid: converted 575,000 packets
train_qos_mid: converted 600,000 packets
train_qos_mid: converted 625,000 packets
train_qos_mid: converted 650,000 packets
train_qos_mid: converted 675,000 packets
train_qos_mid: converted 700,000 packets
train_qos_mid: converted 725,000 packets
train_qos_mid: converted 750,000 packets
train_qos_mid: converted 775,000 packets
train_qos_mid: converted 800,000 packets
train_qos_mid: converted 825,000 packets
train_qos_mid: converted 850,000 packets
train_qos_mid: converted 875,000 packets
train_qos_mid: converted 900,000 packets
train_qos_mid: converted 925,000 packets
train_qos_mid: converted 950,000 packets
train_qos_mid: converted 975,000 packets
train_qos_mid: converted 1,000,000 packets
train_qos_mid: converted 1,025,000 packets
train_qos_mid: converted 1,050,000 packets
train_qos_mid: converted 1,075,000 packets
train_qos_mid: converted 1,100,000 packets
train_qos_mid: converted 1,125,000 packets
train_qos_mid: converted 1,150,000 packets
train_qos_mid: converted 1,175,000 packets
train_qos_mid: converted 1,200,000 packets
train_qos_mid: converted 1,225,000 packets
train_qos_mid: converted 1,250,000 packets
train_qos_mid: converted 1,275,000 packets
train_qos_mid: converted 1,300,000 packets
train_qos_mid: converted 1,325,000 packets
train_qos_mid: converted 1,350,000 packets
train_qos_mid: converted 1,375,000 packets
train_qos_mid: converted 1,400,000 packets
train_qos_mid: converted 1,425,000 packets
train_qos_mid: converted 1,450,000 packets
train_qos_mid: converted 1,475,000 packets
train_qos_mid: converted 1,499,717 packets
Saved and verified train_qos_mid on Drive. Removed its temporary local copy.
Starting train_dollar_char. Local workspace: /content/capture_gate0_work/train_dollar_char_oyq0hlag

Downloading...
From (original): https://drive.google.com/uc?id=1N3IcqQz6tQe-iuvoqWWwVarPCJDK_cpe
From (redirected): https://drive.google.com/uc?id=1N3IcqQz6tQe-iuvoqWWwVarPCJDK_cpe&confirm=t&uuid=1870c2a3-9f6f-4242-ada6-9464bc163fdd
To: /content/capture_gate0_work/20260917T170658_227477Z_full_dev/sources/train_dollar_char/normal_dollar_char_train.csv.part
100%|██████████| 1.97G/1.97G [00:41<00:00, 47.3MB/s]

train_dollar_char: converted 25,000 packets
train_dollar_char: converted 50,000 packets
train_dollar_char: converted 75,000 packets
train_dollar_char: converted 100,000 packets
train_dollar_char: converted 125,000 packets
train_dollar_char: converted 150,000 packets
train_dollar_char: converted 175,000 packets
train_dollar_char: converted 200,000 packets
train_dollar_char: converted 225,000 packets
train_dollar_char: converted 250,000 packets
train_dollar_char: converted 275,000 packets
train_dollar_char: converted 300,000 packets
train_dollar_char: converted 325,000 packets
train_dollar_char: converted 350,000 packets
train_dollar_char: converted 375,000 packets
train_dollar_char: converted 400,000 packets
train_dollar_char: converted 425,000 packets
train_dollar_char: converted 450,000 packets
train_dollar_char: converted 475,000 packets
train_dollar_char: converted 500,000 packets
train_dollar_char: converted 525,000 packets
train_dollar_char: converted 550,000 packets
train_dollar_char: converted 575,000 packets
train_dollar_char: converted 600,000 packets
train_dollar_char: converted 625,000 packets
train_dollar_char: converted 650,000 packets
train_dollar_char: converted 675,000 packets
train_dollar_char: converted 700,000 packets
train_dollar_char: converted 725,000 packets
train_dollar_char: converted 750,000 packets
train_dollar_char: converted 775,000 packets
train_dollar_char: converted 800,000 packets
train_dollar_char: converted 825,000 packets
train_dollar_char: converted 850,000 packets
train_dollar_char: converted 875,000 packets
train_dollar_char: converted 900,000 packets
train_dollar_char: converted 925,000 packets
train_dollar_char: converted 950,000 packets
train_dollar_char: converted 975,000 packets
train_dollar_char: converted 1,000,000 packets
train_dollar_char: converted 1,025,000 packets
train_dollar_char: converted 1,050,000 packets
train_dollar_char: converted 1,075,000 packets
train_dollar_char: converted 1,100,000 packets
train_dollar_char: converted 1,125,000 packets
train_dollar_char: converted 1,150,000 packets
train_dollar_char: converted 1,175,000 packets
train_dollar_char: converted 1,200,000 packets
train_dollar_char: converted 1,225,000 packets
train_dollar_char: converted 1,250,000 packets
train_dollar_char: converted 1,275,000 packets
train_dollar_char: converted 1,300,000 packets
train_dollar_char: converted 1,325,000 packets
train_dollar_char: converted 1,350,000 packets
train_dollar_char: converted 1,375,000 packets
train_dollar_char: converted 1,400,000 packets
train_dollar_char: converted 1,425,000 packets
train_dollar_char: converted 1,450,000 packets
train_dollar_char: converted 1,475,000 packets
train_dollar_char: converted 1,500,000 packets
train_dollar_char: converted 1,525,000 packets
train_dollar_char: converted 1,550,000 packets
train_dollar_char: converted 1,575,000 packets
train_dollar_char: converted 1,600,000 packets
train_dollar_char: converted 1,625,000 packets
train_dollar_char: converted 1,650,000 packets
train_dollar_char: converted 1,675,000 packets
train_dollar_char: converted 1,700,000 packets
train_dollar_char: converted 1,725,000 packets
train_dollar_char: converted 1,750,000 packets
train_dollar_char: converted 1,775,000 packets
train_dollar_char: converted 1,800,000 packets
train_dollar_char: converted 1,825,000 packets
train_dollar_char: converted 1,850,000 packets
train_dollar_char: converted 1,875,000 packets
train_dollar_char: converted 1,900,000 packets
train_dollar_char: converted 1,925,000 packets
train_dollar_char: converted 1,950,000 packets
train_dollar_char: converted 1,975,000 packets
train_dollar_char: converted 2,000,000 packets
train_dollar_char: converted 2,025,000 packets
train_dollar_char: converted 2,050,000 packets
train_dollar_char: converted 2,075,000 packets
train_dollar_char: converted 2,100,000 packets
train_dollar_char: converted 2,125,000 packets
train_dollar_char: converted 2,150,000 packets
train_dollar_char: converted 2,175,000 packets
train_dollar_char: converted 2,200,000 packets
train_dollar_char: converted 2,225,000 packets
train_dollar_char: converted 2,250,000 packets
train_dollar_char: converted 2,275,000 packets
train_dollar_char: converted 2,300,000 packets
train_dollar_char: converted 2,325,000 packets
train_dollar_char: converted 2,350,000 packets
train_dollar_char: converted 2,375,000 packets
train_dollar_char: converted 2,400,000 packets
train_dollar_char: converted 2,425,000 packets
train_dollar_char: converted 2,450,000 packets
train_dollar_char: converted 2,475,000 packets
train_dollar_char: converted 2,500,000 packets
train_dollar_char: converted 2,525,000 packets
train_dollar_char: converted 2,550,000 packets
train_dollar_char: converted 2,575,000 packets
train_dollar_char: converted 2,600,000 packets
train_dollar_char: converted 2,625,000 packets
train_dollar_char: converted 2,650,000 packets
train_dollar_char: converted 2,675,000 packets
train_dollar_char: converted 2,700,000 packets
train_dollar_char: converted 2,725,000 packets
train_dollar_char: converted 2,750,000 packets
train_dollar_char: converted 2,775,000 packets
train_dollar_char: converted 2,800,000 packets
train_dollar_char: converted 2,825,000 packets
train_dollar_char: converted 2,850,000 packets
train_dollar_char: converted 2,875,000 packets
train_dollar_char: converted 2,882,555 packets

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Saved and verified train_dollar_char on Drive. Removed its temporary local copy.
Starting train_slash_char. Local workspace: /content/capture_gate0_work/train_slash_char_vocynj9g

Downloading...
From (original): https://drive.google.com/uc?id=1a0lhWtXsV5i51XCGe0IP7lZURLf9SOD3
From (redirected): https://drive.google.com/uc?id=1a0lhWtXsV5i51XCGe0IP7lZURLf9SOD3&confirm=t&uuid=850be6af-750d-4c19-91ec-7e5c86048f91
To: /content/capture_gate0_work/20260917T170658_227477Z_full_dev/sources/train_slash_char/normal_slash_char_train.csv.part
100%|██████████| 5.10G/5.10G [01:42<00:00, 49.6MB/s]

train_slash_char: converted 25,000 packets
train_slash_char: converted 50,000 packets
train_slash_char: converted 75,000 packets
train_slash_char: converted 100,000 packets
train_slash_char: converted 125,000 packets
train_slash_char: converted 150,000 packets
train_slash_char: converted 175,000 packets
train_slash_char: converted 200,000 packets
train_slash_char: converted 225,000 packets
train_slash_char: converted 250,000 packets
train_slash_char: converted 275,000 packets
train_slash_char: converted 300,000 packets
train_slash_char: converted 325,000 packets
train_slash_char: converted 350,000 packets
train_slash_char: converted 375,000 packets
train_slash_char: converted 400,000 packets
train_slash_char: converted 425,000 packets
train_slash_char: converted 450,000 packets
train_slash_char: converted 475,000 packets
train_slash_char: converted 500,000 packets
train_slash_char: converted 525,000 packets
train_slash_char: converted 550,000 packets
train_slash_char: converted 575,000 packets
train_slash_char: converted 600,000 packets
train_slash_char: converted 625,000 packets
train_slash_char: converted 650,000 packets
train_slash_char: converted 675,000 packets
train_slash_char: converted 700,000 packets
train_slash_char: converted 725,000 packets
train_slash_char: converted 750,000 packets
train_slash_char: converted 775,000 packets
train_slash_char: converted 800,000 packets
train_slash_char: converted 825,000 packets
train_slash_char: converted 850,000 packets
train_slash_char: converted 875,000 packets
train_slash_char: converted 900,000 packets
train_slash_char: converted 925,000 packets
train_slash_char: converted 950,000 packets
train_slash_char: converted 975,000 packets
train_slash_char: converted 1,000,000 packets
train_slash_char: converted 1,025,000 packets
train_slash_char: converted 1,050,000 packets
train_slash_char: converted 1,075,000 packets
train_slash_char: converted 1,100,000 packets
train_slash_char: converted 1,125,000 packets
train_slash_char: converted 1,150,000 packets
train_slash_char: converted 1,175,000 packets
train_slash_char: converted 1,200,000 packets
train_slash_char: converted 1,225,000 packets
train_slash_char: converted 1,250,000 packets
train_slash_char: converted 1,275,000 packets
train_slash_char: converted 1,300,000 packets
train_slash_char: converted 1,325,000 packets
train_slash_char: converted 1,350,000 packets
train_slash_char: converted 1,375,000 packets
train_slash_char: converted 1,400,000 packets
train_slash_char: converted 1,425,000 packets
train_slash_char: converted 1,450,000 packets
train_slash_char: converted 1,475,000 packets
train_slash_char: converted 1,500,000 packets
train_slash_char: converted 1,525,000 packets
train_slash_char: converted 1,550,000 packets
train_slash_char: converted 1,575,000 packets
train_slash_char: converted 1,600,000 packets
train_slash_char: converted 1,625,000 packets
train_slash_char: converted 1,650,000 packets
train_slash_char: converted 1,675,000 packets
train_slash_char: converted 1,700,000 packets
train_slash_char: converted 1,725,000 packets
train_slash_char: converted 1,750,000 packets
train_slash_char: converted 1,775,000 packets
train_slash_char: converted 1,800,000 packets
train_slash_char: converted 1,825,000 packets
train_slash_char: converted 1,850,000 packets
train_slash_char: converted 1,875,000 packets
train_slash_char: converted 1,900,000 packets
train_slash_char: converted 1,925,000 packets
train_slash_char: converted 1,950,000 packets
train_slash_char: converted 1,975,000 packets
train_slash_char: converted 2,000,000 packets
train_slash_char: converted 2,025,000 packets
train_slash_char: converted 2,050,000 packets
train_slash_char: converted 2,075,000 packets
train_slash_char: converted 2,100,000 packets
train_slash_char: converted 2,125,000 packets
train_slash_char: converted 2,150,000 packets
train_slash_char: converted 2,175,000 packets
train_slash_char: converted 2,200,000 packets
train_slash_char: converted 2,225,000 packets
train_slash_char: converted 2,250,000 packets
train_slash_char: converted 2,275,000 packets
train_slash_char: converted 2,300,000 packets
train_slash_char: converted 2,325,000 packets
train_slash_char: converted 2,350,000 packets
train_slash_char: converted 2,375,000 packets
train_slash_char: converted 2,400,000 packets
train_slash_char: converted 2,425,000 packets
train_slash_char: converted 2,450,000 packets
train_slash_char: converted 2,475,000 packets
train_slash_char: converted 2,500,000 packets
train_slash_char: converted 2,525,000 packets
train_slash_char: converted 2,550,000 packets
train_slash_char: converted 2,575,000 packets
train_slash_char: converted 2,600,000 packets
train_slash_char: converted 2,625,000 packets
train_slash_char: converted 2,650,000 packets
train_slash_char: converted 2,675,000 packets
train_slash_char: converted 2,700,000 packets
train_slash_char: converted 2,725,000 packets
train_slash_char: converted 2,750,000 packets
train_slash_char: converted 2,775,000 packets
train_slash_char: converted 2,800,000 packets
train_slash_char: converted 2,825,000 packets
train_slash_char: converted 2,850,000 packets
train_slash_char: converted 2,875,000 packets
train_slash_char: converted 2,900,000 packets
train_slash_char: converted 2,925,000 packets
train_slash_char: converted 2,950,000 packets
train_slash_char: converted 2,975,000 packets
train_slash_char: converted 3,000,000 packets
train_slash_char: converted 3,025,000 packets
train_slash_char: converted 3,050,000 packets
train_slash_char: converted 3,075,000 packets
train_slash_char: converted 3,100,000 packets
train_slash_char: converted 3,125,000 packets
train_slash_char: converted 3,150,000 packets
train_slash_char: converted 3,175,000 packets
train_slash_char: converted 3,200,000 packets
train_slash_char: converted 3,225,000 packets
train_slash_char: converted 3,250,000 packets
train_slash_char: converted 3,275,000 packets
train_slash_char: converted 3,300,000 packets
train_slash_char: converted 3,325,000 packets
train_slash_char: converted 3,350,000 packets
train_slash_char: converted 3,375,000 packets
train_slash_char: converted 3,400,000 packets
train_slash_char: converted 3,425,000 packets
train_slash_char: converted 3,450,000 packets
train_slash_char: converted 3,475,000 packets
train_slash_char: converted 3,500,000 packets
train_slash_char: converted 3,525,000 packets
train_slash_char: converted 3,550,000 packets
train_slash_char: converted 3,575,000 packets
train_slash_char: converted 3,600,000 packets
train_slash_char: converted 3,625,000 packets
train_slash_char: converted 3,650,000 packets
train_slash_char: converted 3,675,000 packets
train_slash_char: converted 3,700,000 packets
train_slash_char: converted 3,725,000 packets
train_slash_char: converted 3,750,000 packets
train_slash_char: converted 3,775,000 packets
train_slash_char: converted 3,800,000 packets
train_slash_char: converted 3,825,000 packets
train_slash_char: converted 3,850,000 packets
train_slash_char: converted 3,875,000 packets
train_slash_char: converted 3,900,000 packets
train_slash_char: converted 3,925,000 packets
train_slash_char: converted 3,950,000 packets
train_slash_char: converted 3,975,000 packets
train_slash_char: converted 4,000,000 packets
train_slash_char: converted 4,025,000 packets
train_slash_char: converted 4,050,000 packets
train_slash_char: converted 4,075,000 packets
train_slash_char: converted 4,100,000 packets
train_slash_char: converted 4,125,000 packets
train_slash_char: converted 4,150,000 packets
train_slash_char: converted 4,175,000 packets
train_slash_char: converted 4,200,000 packets
train_slash_char: converted 4,225,000 packets
train_slash_char: converted 4,250,000 packets
train_slash_char: converted 4,275,000 packets
train_slash_char: converted 4,300,000 packets
train_slash_char: converted 4,325,000 packets
train_slash_char: converted 4,350,000 packets
train_slash_char: converted 4,375,000 packets
train_slash_char: converted 4,400,000 packets
train_slash_char: converted 4,425,000 packets
train_slash_char: converted 4,450,000 packets
train_slash_char: converted 4,475,000 packets
train_slash_char: converted 4,500,000 packets
train_slash_char: converted 4,525,000 packets
train_slash_char: converted 4,550,000 packets
train_slash_char: converted 4,575,000 packets
train_slash_char: converted 4,600,000 packets
train_slash_char: converted 4,625,000 packets
train_slash_char: converted 4,650,000 packets
train_slash_char: converted 4,675,000 packets
train_slash_char: converted 4,700,000 packets
train_slash_char: converted 4,725,000 packets
train_slash_char: converted 4,750,000 packets
train_slash_char: converted 4,775,000 packets
train_slash_char: converted 4,800,000 packets
train_slash_char: converted 4,825,000 packets
train_slash_char: converted 4,850,000 packets
train_slash_char: converted 4,875,000 packets
train_slash_char: converted 4,900,000 packets
train_slash_char: converted 4,925,000 packets
train_slash_char: converted 4,950,000 packets
train_slash_char: converted 4,975,000 packets
train_slash_char: converted 5,000,000 packets
train_slash_char: converted 5,025,000 packets
train_slash_char: converted 5,050,000 packets
train_slash_char: converted 5,075,000 packets
train_slash_char: converted 5,100,000 packets
train_slash_char: converted 5,125,000 packets
train_slash_char: converted 5,150,000 packets
train_slash_char: converted 5,175,000 packets
train_slash_char: converted 5,200,000 packets
train_slash_char: converted 5,225,000 packets
train_slash_char: converted 5,250,000 packets
train_slash_char: converted 5,275,000 packets
train_slash_char: converted 5,300,000 packets
train_slash_char: converted 5,325,000 packets
train_slash_char: converted 5,350,000 packets
train_slash_char: converted 5,375,000 packets
train_slash_char: converted 5,400,000 packets
train_slash_char: converted 5,425,000 packets
train_slash_char: converted 5,450,000 packets
train_slash_char: converted 5,475,000 packets
train_slash_char: converted 5,500,000 packets
train_slash_char: converted 5,525,000 packets
train_slash_char: converted 5,550,000 packets
train_slash_char: converted 5,575,000 packets
train_slash_char: converted 5,600,000 packets
train_slash_char: converted 5,625,000 packets
train_slash_char: converted 5,650,000 packets
train_slash_char: converted 5,675,000 packets
train_slash_char: converted 5,700,000 packets
train_slash_char: converted 5,725,000 packets
train_slash_char: converted 5,750,000 packets
train_slash_char: converted 5,775,000 packets
train_slash_char: converted 5,800,000 packets
train_slash_char: converted 5,825,000 packets
train_slash_char: converted 5,850,000 packets
train_slash_char: converted 5,875,000 packets
train_slash_char: converted 5,900,000 packets
train_slash_char: converted 5,925,000 packets
train_slash_char: converted 5,950,000 packets
train_slash_char: converted 5,975,000 packets
train_slash_char: converted 6,000,000 packets
train_slash_char: converted 6,025,000 packets
train_slash_char: converted 6,050,000 packets
train_slash_char: converted 6,075,000 packets
train_slash_char: converted 6,100,000 packets
train_slash_char: converted 6,125,000 packets
train_slash_char: converted 6,150,000 packets
train_slash_char: converted 6,175,000 packets
train_slash_char: converted 6,200,000 packets
train_slash_char: converted 6,225,000 packets
train_slash_char: converted 6,250,000 packets
train_slash_char: converted 6,275,000 packets
train_slash_char: converted 6,300,000 packets
train_slash_char: converted 6,325,000 packets
train_slash_char: converted 6,350,000 packets
train_slash_char: converted 6,375,000 packets
train_slash_char: converted 6,400,000 packets
train_slash_char: converted 6,425,000 packets
train_slash_char: converted 6,425,516 packets

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Saved and verified train_slash_char on Drive. Removed its temporary local copy.
Starting train_sub_exf. Local workspace: /content/capture_gate0_work/train_sub_exf_h449vl_u

Downloading...
From (original): https://drive.google.com/uc?id=1YJzcazSvs987g1xPWal8gxBpqeYfcSp4
From (redirected): https://drive.google.com/uc?id=1YJzcazSvs987g1xPWal8gxBpqeYfcSp4&confirm=t&uuid=1ccedb33-a498-4c0e-8a12-27fb38a1a30a
To: /content/capture_gate0_work/20260917T170658_227477Z_full_dev/sources/train_sub_exf/normal_sub_exf_train.csv.part
100%|██████████| 1.66G/1.66G [00:46<00:00, 35.7MB/s]

train_sub_exf: converted 25,000 packets
train_sub_exf: converted 50,000 packets
train_sub_exf: converted 75,000 packets
train_sub_exf: converted 100,000 packets
train_sub_exf: converted 125,000 packets
train_sub_exf: converted 150,000 packets
train_sub_exf: converted 175,000 packets
train_sub_exf: converted 200,000 packets
train_sub_exf: converted 225,000 packets
train_sub_exf: converted 250,000 packets
train_sub_exf: converted 275,000 packets
train_sub_exf: converted 300,000 packets
train_sub_exf: converted 325,000 packets
train_sub_exf: converted 350,000 packets
train_sub_exf: converted 375,000 packets
train_sub_exf: converted 400,000 packets
train_sub_exf: converted 425,000 packets
train_sub_exf: converted 450,000 packets
train_sub_exf: converted 475,000 packets
train_sub_exf: converted 500,000 packets
train_sub_exf: converted 525,000 packets
train_sub_exf: converted 550,000 packets
train_sub_exf: converted 575,000 packets
train_sub_exf: converted 600,000 packets
train_sub_exf: converted 625,000 packets
train_sub_exf: converted 650,000 packets
train_sub_exf: converted 675,000 packets
train_sub_exf: converted 700,000 packets
train_sub_exf: converted 725,000 packets
train_sub_exf: converted 750,000 packets
train_sub_exf: converted 775,000 packets
train_sub_exf: converted 800,000 packets
train_sub_exf: converted 825,000 packets
train_sub_exf: converted 850,000 packets
train_sub_exf: converted 875,000 packets
train_sub_exf: converted 900,000 packets
train_sub_exf: converted 925,000 packets
train_sub_exf: converted 950,000 packets
train_sub_exf: converted 975,000 packets
train_sub_exf: converted 1,000,000 packets
train_sub_exf: converted 1,025,000 packets
train_sub_exf: converted 1,050,000 packets
train_sub_exf: converted 1,075,000 packets
train_sub_exf: converted 1,100,000 packets
train_sub_exf: converted 1,125,000 packets
train_sub_exf: converted 1,150,000 packets
train_sub_exf: converted 1,175,000 packets
train_sub_exf: converted 1,200,000 packets
train_sub_exf: converted 1,225,000 packets
train_sub_exf: converted 1,250,000 packets
train_sub_exf: converted 1,275,000 packets
train_sub_exf: converted 1,300,000 packets
train_sub_exf: converted 1,325,000 packets
train_sub_exf: converted 1,350,000 packets
train_sub_exf: converted 1,375,000 packets
train_sub_exf: converted 1,400,000 packets
train_sub_exf: converted 1,425,000 packets
train_sub_exf: converted 1,450,000 packets
train_sub_exf: converted 1,475,000 packets
train_sub_exf: converted 1,500,000 packets
train_sub_exf: converted 1,525,000 packets
train_sub_exf: converted 1,550,000 packets
train_sub_exf: converted 1,575,000 packets
train_sub_exf: converted 1,600,000 packets
train_sub_exf: converted 1,625,000 packets
train_sub_exf: converted 1,650,000 packets
train_sub_exf: converted 1,675,000 packets
train_sub_exf: converted 1,700,000 packets
train_sub_exf: converted 1,725,000 packets
train_sub_exf: converted 1,750,000 packets
train_sub_exf: converted 1,775,000 packets
train_sub_exf: converted 1,800,000 packets
train_sub_exf: converted 1,825,000 packets
train_sub_exf: converted 1,850,000 packets
train_sub_exf: converted 1,875,000 packets
train_sub_exf: converted 1,900,000 packets
train_sub_exf: converted 1,925,000 packets
train_sub_exf: converted 1,950,000 packets
train_sub_exf: converted 1,975,000 packets
train_sub_exf: converted 2,000,000 packets
train_sub_exf: converted 2,025,000 packets
train_sub_exf: converted 2,050,000 packets
train_sub_exf: converted 2,075,000 packets
train_sub_exf: converted 2,100,000 packets
train_sub_exf: converted 2,125,000 packets
train_sub_exf: converted 2,150,000 packets
train_sub_exf: converted 2,175,000 packets
train_sub_exf: converted 2,200,000 packets
train_sub_exf: converted 2,225,000 packets
train_sub_exf: converted 2,225,807 packets
Saved and verified train_sub_exf on Drive. Removed its temporary local copy.
{
  "train_empty_conn": {
    "status": "review_required",
    "blockers": [],
    "report": "/content/drive/MyDrive/capture_gate0/runs/20260917T170658_227477Z_full_dev/train_empty_conn/audit_report.json"
  },
  "train_qos_mid": {
    "status": "review_required",
    "blockers": [],
    "report": "/content/drive/MyDrive/capture_gate0/runs/20260917T170658_227477Z_full_dev/train_qos_mid/audit_report.json"
  },
  "train_dollar_char": {
    "status": "review_required",
    "blockers": [],
    "report": "/content/drive/MyDrive/capture_gate0/runs/20260917T170658_227477Z_full_dev/train_dollar_char/audit_report.json"
  },
  "train_slash_char": {
    "status": "review_required",
    "blockers": [],
    "report": "/content/drive/MyDrive/capture_gate0/runs/20260917T170658_227477Z_full_dev/train_slash_char/audit_report.json"
  },
  "train_sub_exf": {
    "status": "review_required",
    "blockers": [],
    "report": "/content/drive/MyDrive/capture_gate0/runs/20260917T170658_227477Z_full_dev/train_sub_exf/audit_report.json"
  }
}

## 7. Review the saved reports

The run directory contains the manifest snapshot, resolved runtime configuration, Git provenance, run status, and per-scenario artifacts:

- `audit_report.json`: schema, packet counts, raw labels, column diagnostics, blockers, and window summaries.
- `packets.audit.parquet`: all rows and raw fields, plus canonical diagnostic metadata (optional durable retention).
- `attack_iterations.parquet`: counts and durations grouped by attack step, phase, and sequence.
- `windows_*s_offset_*s.parquet`: occupied-window packet, node, and directed-pair counts.
- `artifact_checksums.json`: hashes of the persisted files.

A zero-duration attack iteration is possible when all its packets have the same timestamp. Duplicate benign data across scenarios sharing the same benign source is not removed; the manifest's background-separated folds address that evaluation risk.

In [ ]:
REPORTS = {}
for scenario, result in RESULTS.items():
    report = json.loads(Path(result["report"]).read_text())
    REPORTS[scenario] = report
    print(f"\n{scenario}: {report['status']}")
    print(f"Blockers: {report['blockers']}")
    display(pd.DataFrame([report["counts"]]))
    display(pd.DataFrame(report["raw_labels"]))
    window_summary = pd.DataFrame(report["windows"])
    window_summary["mean_packets_per_second_occupied"] = (
        window_summary["mean_packets_occupied"] / window_summary["width_seconds"]
    )
    display(window_summary)
    display(pd.DataFrame(report["column_profiles"]).T)
    print("Duplicate column groups:", report["duplicate_column_groups_sha256"])
    iterations = pd.read_parquet(Path(result["report"]).parent / "attack_iterations.parquet")
    display(iterations.head(50))

train_empty_conn: review_required
Blockers: []

,packets,normal_packets,attack_packets,unmapped_labels,invalid_timestamps,missing_endpoints,incomplete_attack_annotations,first_timestamp_seconds,last_timestamp_seconds,duplicate_raw_rows_sha256,unique_endpoints,unique_directed_pairs
0,1175779,746806,428973,0,0,0,0,0.019792,46799.813163,0,160,623

            raw_label  packets
0              normal   746806
1          nmap_10_T4   255667
2  brute_force_timing   107515
3     empty_conn_ddos    28269
4           nmap_mqtt    14168
5         nmap_banner    12649
6          empty_conn     6650
7            nmap_sub     2277
8            mqtt_cat     1171
9           sftp_inst      607

,width_seconds,origin_offset_seconds,artifact,occupied_windows,empty_windows_between_first_and_last,mean_packets_occupied,max_packets,packet_quantiles_occupied,max_nodes,node_quantiles_occupied,max_directed_pairs,pair_quantiles_occupied,mean_packets_per_second_occupied
0,1,0.0,windows_1s_offset_0s.parquet,44480,2320,26.433880,15524,"[16.0, 37.0, 145.41999999999825]",56,"[4.0, 8.0, 10.0]",96,"[5.0, 11.0, 14.0]",26.433880
1,1,0.5,windows_1s_offset_0.5s.parquet,44435,2366,26.460650,15616,"[16.0, 37.0, 146.0]",67,"[4.0, 8.0, 11.0]",92,"[5.0, 11.0, 14.659999999996217]",26.460650
2,5,0.0,windows_5s_offset_0s.parquet,9360,0,125.617415,42145,"[79.0, 134.04999999999927, 616.4099999999999]",86,"[13.0, 20.0, 33.0]",108,"[20.0, 31.0, 40.409999999999854]",25.123483
3,5,2.5,windows_5s_offset_2.5s.parquet,9361,0,125.603995,42148,"[79.0, 132.0, 616.1999999999989]",80,"[13.0, 20.0, 33.0]",106,"[20.0, 31.0, 40.0]",25.120799
4,10,0.0,windows_10s_offset_0s.parquet,4680,0,251.234829,42245,"[159.0, 261.10000000000036, 920.0]",88,"[15.0, 22.0, 37.0]",111,"[24.0, 37.0, 62.0]",25.123483
5,10,5.0,windows_10s_offset_5s.parquet,4681,0,251.181158,42231,"[161.0, 267.0, 874.1999999999998]",86,"[15.0, 22.0, 37.0]",115,"[24.0, 36.0, 60.19999999999982]",25.118116
6,30,0.0,windows_30s_offset_0s.parquet,1560,0,753.704487,42592,"[490.5, 1032.1, 1678.4400000000069]",95,"[19.0, 37.0, 45.0]",162,"[30.0, 52.0, 74.23000000000025]",25.123483
7,30,15.0,windows_30s_offset_15s.parquet,1561,0,753.221653,43255,"[492.0, 1027.0, 1633.0000000000018]",93,"[19.0, 38.0, 45.40000000000009]",132,"[31.0, 53.0, 77.0]",25.107388

,missing,numeric_values,constant_nonmissing,numeric_parse_failures_nonmissing,interpretation
layers_frame_frame.section_number,0,1175779,True,0,Parse failures may be valid categorical values...
timestamp,0,0,False,1175779,Parse failures may be valid categorical values...
layers_frame_frame.time_epoch,0,1175779,False,0,Parse failures may be valid categorical values...
layers_frame_frame.number,0,1175779,False,0,Parse failures may be valid categorical values...
layers_frame_frame.len,0,1175779,False,0,Parse failures may be valid categorical values...
...,...,...,...,...,...
phase_idx,746806,428973,False,0,Parse failures may be valid categorical values...
phase_name,746806,0,False,428973,Parse failures may be valid categorical values...
phase_number,746806,428973,False,0,Parse failures may be valid categorical values...
step_number,746806,428973,False,0,Parse failures may be valid categorical values...
sequence_id,746806,428973,False,0,Parse failures may be valid categorical values...

Duplicate column groups: [['layers_frame_frame.len', 'layers_frame_frame.cap_len'], ['layers_eth_eth.dst', 'layers_eth_eth.dst_tree_eth.addr'], ['layers_eth_eth.dst_tree_eth.dst_resolved', 'layers_eth_eth.dst_tree_eth.addr_resolved'], ['layers_eth_eth.dst_tree_eth.dst.oui', 'layers_eth_eth.dst_tree_eth.addr.oui'], ['layers_eth_eth.src', 'layers_eth_eth.src_tree_eth.src_resolved'], ['layers_eth_eth.src_tree_eth.src.oui', 'layers_eth_eth.src_tree_eth.addr.oui'], ['layers_ipv6_ipv6.addr', 'layers_ipv6_ipv6.host'], ['layers_ip_ip.addr', 'layers_ip_ip.host'], ['layers_tcp_tcp.dstport', 'layers_tcp_tcp.port'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_server_to_client']]

,attack_step,phase,sequence_id,packets,start_seconds,end_seconds,duration_seconds
0,nmap_10_T4,RECONNAISSANCE,2.11,42683,1194.189266,1250.932538,56.743272
1,nmap_10_T4,RECONNAISSANCE,10.11,42579,1896.797980,1953.323450,56.525470
2,brute_force_timing,BRUTE_FORCE,14.11,107515,2198.502349,3246.934789,1048.432440
3,nmap_banner,DISCOVERY,20.11,903,3563.283668,3627.617833,64.334165
4,nmap_mqtt,DISCOVERY,29.11,963,4069.121063,4311.563229,242.442166
5,nmap_mqtt,DISCOVERY,33.11,975,4712.317918,4954.696390,242.378472
6,sftp_inst,INSTALLATION,73.11,50,6142.140385,6142.306323,0.165938
7,sftp_inst,INSTALLATION,86.11,51,6657.194654,6657.360399,0.165745
8,empty_conn,EXPLOIT,88.11,179,6749.610302,6853.893278,104.282976
9,empty_conn,EXPLOIT,90.11,168,6900.041715,6981.729900,81.688185
10,empty_conn,EXPLOIT,92.11,182,7016.321228,7103.990313,87.669085
11,empty_conn,EXPLOIT,94.11,172,7190.987985,7282.284307,91.296322
12,nmap_mqtt,DISCOVERY,97.11,971,7324.856994,7567.271709,242.414715
13,nmap_banner,DISCOVERY,126.11,899,9765.188287,9829.533080,64.344793
14,empty_conn,EXPLOIT,130.11,147,10060.773091,10149.729002,88.955911
15,empty_conn,EXPLOIT,132.11,182,10213.595769,10308.952727,95.356958
16,nmap_mqtt,DISCOVERY,149.11,925,11649.420002,11891.798644,242.378642
17,nmap_banner,DISCOVERY,152.11,914,11961.690698,12026.064633,64.373935
18,empty_conn,EXPLOIT,154.11,209,12113.878038,12222.296393,108.418355
19,empty_conn,EXPLOIT,156.11,214,12302.347943,12416.494349,114.146406
20,empty_conn,EXPLOIT,158.11,213,12478.851152,12587.387422,108.536270
21,nmap_mqtt,DISCOVERY,163.11,921,12829.780007,13072.233256,242.453249
22,empty_conn,EXPLOIT,181.11,179,14437.516116,14542.350017,104.833901
23,empty_conn,EXPLOIT,183.11,199,14638.307810,14749.525010,111.217200
24,nmap_mqtt,DISCOVERY,188.11,929,14942.083164,15184.486027,242.402863
25,empty_conn,EXPLOIT,199.11,184,15780.976422,15880.554750,99.578328
26,empty_conn_ddos,EXPLOIT,213.11,3983,16943.714654,19367.774506,2424.059852
27,empty_conn_ddos,EXPLOIT,217.11,3990,22006.092143,24400.395208,2394.303065
28,empty_conn_ddos,EXPLOIT,219.11,4077,24496.297151,26948.564593,2452.267442
29,empty_conn_ddos,EXPLOIT,223.11,4068,29536.059719,31986.653427,2450.593708
30,nmap_mqtt,DISCOVERY,226.11,967,32182.684818,32425.082859,242.398041
31,mqtt_cat,DISCOVERY,39.11,95,5118.411836,5123.630913,5.219077
32,mqtt_cat,DISCOVERY,41.11,103,5161.464968,5167.254642,5.789674
33,mqtt_cat,DISCOVERY,44.11,94,5254.004766,5259.224168,5.219402
34,mqtt_cat,DISCOVERY,53.11,97,5540.121570,5545.347753,5.226183
35,mqtt_cat,DISCOVERY,57.11,109,5710.210797,5715.511981,5.301184
36,mqtt_cat,DISCOVERY,59.11,97,5760.331954,5765.826001,5.494047
37,sftp_inst,INSTALLATION,63.11,50,5849.007622,5849.171068,0.163446
38,sftp_inst,INSTALLATION,65.11,53,5888.269360,5888.435423,0.166063
39,sftp_inst,INSTALLATION,70.11,50,6047.959223,6048.125463,0.166240
40,empty_conn,EXPLOIT,102.11,207,7797.106403,7893.088960,95.982557
41,empty_conn,EXPLOIT,104.11,150,7943.697157,8022.465574,78.768417
42,empty_conn,EXPLOIT,109.11,159,8185.607510,8278.107303,92.499793
43,nmap_mqtt,DISCOVERY,111.11,926,8327.774806,8570.183451,242.408645
44,nmap_mqtt,DISCOVERY,136.11,924,10558.347674,10800.745400,242.397726
45,nmap_banner,DISCOVERY,138.11,900,10855.229581,10919.585574,64.355993
46,empty_conn,EXPLOIT,140.11,179,10971.494616,11061.443769,89.949153
47,empty_conn,EXPLOIT,142.11,195,11155.376282,11252.776023,97.399741
48,empty_conn,EXPLOIT,144.11,198,11350.569706,11460.831281,110.261575
49,nmap_banner,DISCOVERY,165.11,899,13142.860356,13207.196999,64.336643

train_qos_mid: review_required
Blockers: []

,packets,normal_packets,attack_packets,unmapped_labels,invalid_timestamps,missing_endpoints,incomplete_attack_annotations,first_timestamp_seconds,last_timestamp_seconds,duplicate_raw_rows_sha256,unique_endpoints,unique_directed_pairs
0,1499717,746806,752911,0,0,0,0,0.019792,46799.813163,0,163,481

               raw_label  packets
0                 normal   746806
1             nmap_10_T5   425805
2           qos_mid_ddos   257148
3  brute_force_malformed    30860
4                qos_mid    12477
5               nmap_sub     8753
6              nmap_mqtt     8458
7            nmap_banner     8188
8               mqtt_cat      955
9               scp_inst      267

,width_seconds,origin_offset_seconds,artifact,occupied_windows,empty_windows_between_first_and_last,mean_packets_occupied,max_packets,packet_quantiles_occupied,max_nodes,node_quantiles_occupied,max_directed_pairs,pair_quantiles_occupied,mean_packets_per_second_occupied
0,1,0.0,windows_1s_offset_0s.parquet,45154,1646,33.213381,14815,"[21.0, 45.0, 75.0]",56,"[5.0, 9.0, 11.0]",96,"[6.0, 13.0, 16.0]",33.213381
1,1,0.5,windows_1s_offset_0.5s.parquet,45107,1694,33.247988,14642,"[21.0, 45.0, 75.0]",67,"[5.0, 9.0, 11.0]",92,"[6.0, 13.0, 16.0]",33.247988
2,5,0.0,windows_5s_offset_0s.parquet,9360,0,160.226175,42191,"[99.0, 183.0, 612.0]",86,"[13.0, 19.0, 32.0]",108,"[21.0, 32.0, 41.0]",32.045235
3,5,2.5,windows_5s_offset_2.5s.parquet,9361,0,160.209059,42125,"[99.0, 183.0, 614.3999999999996]",80,"[13.0, 19.0, 32.0]",106,"[21.0, 32.0, 41.0]",32.041812
4,10,0.0,windows_10s_offset_0s.parquet,4680,0,320.452350,42322,"[197.0, 354.0500000000002, 826.0]",88,"[15.0, 22.0, 36.0]",111,"[24.0, 38.0, 60.0]",32.045235
5,10,5.0,windows_10s_offset_5s.parquet,4681,0,320.383892,42891,"[198.0, 362.0, 825.9999999999945]",86,"[15.0, 22.0, 36.19999999999982]",115,"[24.0, 38.0, 60.0]",32.038389
6,30,0.0,windows_30s_offset_0s.parquet,1560,0,961.357051,43222,"[638.5, 1104.1499999999999, 2001.4700000000055]",95,"[19.0, 38.0, 45.0]",162,"[31.0, 56.049999999999955, 74.41000000000008]",32.045235
7,30,15.0,windows_30s_offset_15s.parquet,1561,0,960.741192,43284,"[632.0, 1067.0, 2038.6000000000008]",93,"[19.0, 37.0, 45.0]",132,"[31.0, 53.0, 76.0]",32.024706

,missing,numeric_values,constant_nonmissing,numeric_parse_failures_nonmissing,interpretation
layers_frame_frame.section_number,0,1499717,True,0,Parse failures may be valid categorical values...
timestamp,0,0,False,1499717,Parse failures may be valid categorical values...
layers_frame_frame.time_epoch,0,1499717,False,0,Parse failures may be valid categorical values...
layers_frame_frame.number,0,1499717,False,0,Parse failures may be valid categorical values...
layers_frame_frame.len,0,1499717,False,0,Parse failures may be valid categorical values...
...,...,...,...,...,...
phase_idx,746806,752911,False,0,Parse failures may be valid categorical values...
phase_name,746806,0,False,752911,Parse failures may be valid categorical values...
phase_number,746806,752911,False,0,Parse failures may be valid categorical values...
step_number,746806,752911,False,0,Parse failures may be valid categorical values...
sequence_id,746806,752911,False,0,Parse failures may be valid categorical values...

Duplicate column groups: [['layers_frame_frame.len', 'layers_frame_frame.cap_len'], ['layers_eth_eth.dst', 'layers_eth_eth.dst_tree_eth.addr'], ['layers_eth_eth.dst_tree_eth.dst_resolved', 'layers_eth_eth.dst_tree_eth.addr_resolved'], ['layers_eth_eth.dst_tree_eth.dst.oui', 'layers_eth_eth.dst_tree_eth.addr.oui'], ['layers_eth_eth.src', 'layers_eth_eth.src_tree_eth.src_resolved'], ['layers_eth_eth.src_tree_eth.src.oui', 'layers_eth_eth.src_tree_eth.addr.oui'], ['layers_ipv6_ipv6.addr', 'layers_ipv6_ipv6.host'], ['layers_ip_ip.addr', 'layers_ip_ip.host'], ['layers_tcp_tcp.dstport', 'layers_tcp_tcp.port'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_server_to_client']]

,attack_step,phase,sequence_id,packets,start_seconds,end_seconds,duration_seconds
0,nmap_sub,DISCOVERY,34.13,727,2995.572083,3049.962025,54.389942
1,mqtt_cat,DISCOVERY,36.13,93,3090.329460,3095.547665,5.218205
2,mqtt_cat,DISCOVERY,41.13,92,3290.924753,3296.147223,5.222470
3,mqtt_cat,DISCOVERY,43.13,95,3350.914563,3356.135161,5.220598
4,scp_inst,INSTALLATION,47.13,53,3502.374518,3502.569303,0.194785
5,scp_inst,INSTALLATION,51.13,55,3620.349441,3620.570555,0.221114
6,scp_inst,INSTALLATION,55.13,54,3771.422783,3771.616420,0.193637
7,qos_mid,EXPLOIT,62.13,47,4010.266521,4011.281231,1.014710
8,qos_mid,EXPLOIT,67.13,274,4182.675199,4200.844492,18.169293
9,qos_mid,EXPLOIT,94.13,383,5737.525255,5763.092012,25.566757
10,qos_mid,EXPLOIT,96.13,417,5816.676137,5843.814560,27.138423
11,qos_mid,EXPLOIT,98.13,282,5900.323986,5918.165967,17.841981
12,qos_mid,EXPLOIT,106.13,210,6510.961680,6523.818141,12.856461
13,nmap_mqtt,DISCOVERY,134.13,932,7892.314844,8134.684497,242.369653
14,qos_mid,EXPLOIT,136.13,291,8199.087112,8218.328100,19.240988
15,qos_mid,EXPLOIT,140.13,590,8369.701629,8411.686556,41.984927
16,qos_mid,EXPLOIT,144.13,336,8603.518685,8625.564097,22.045412
17,qos_mid,EXPLOIT,150.13,402,9034.529258,9061.967030,27.437772
18,nmap_mqtt,DISCOVERY,152.13,931,9113.379752,9355.755629,242.375877
19,qos_mid,EXPLOIT,154.13,407,9424.252651,9450.003193,25.750542
20,brute_force_malformed,BRUTE_FORCE,163.13,15391,10034.380339,10894.637576,860.257237
21,qos_mid,EXPLOIT,165.13,428,10963.097563,10991.654169,28.556606
22,nmap_sub,DISCOVERY,167.13,754,11062.749083,11117.646954,54.897871
23,qos_mid_ddos,EXPLOIT,176.13,3651,12080.020503,12332.578445,252.557942
24,qos_mid_ddos,EXPLOIT,178.13,3038,12407.989594,12618.679340,210.689746
25,qos_mid_ddos,EXPLOIT,182.13,3446,13022.978394,13260.938125,237.959731
26,nmap_sub,DISCOVERY,187.13,723,13427.391117,13481.781158,54.390041
27,qos_mid_ddos,EXPLOIT,189.13,3451,13524.515750,13763.404770,238.889020
28,qos_mid_ddos,EXPLOIT,197.13,3321,14454.016490,14684.772043,230.755553
29,qos_mid_ddos,EXPLOIT,199.13,3762,14766.938849,15027.455826,260.516977
30,nmap_10_T5,RECONNAISSANCE,205.13,42575,15707.336921,15762.992678,55.655757
31,qos_mid_ddos,EXPLOIT,232.13,3970,18540.317932,18813.242883,272.924951
32,qos_mid_ddos,EXPLOIT,236.13,3686,19121.293186,19378.311718,257.018532
33,qos_mid_ddos,EXPLOIT,238.13,3656,19428.454320,19682.859129,254.404809
34,qos_mid_ddos,EXPLOIT,248.13,3246,20625.923087,20850.321292,224.398205
35,qos_mid_ddos,EXPLOIT,250.13,3566,20928.575541,21175.032211,246.456670
36,qos_mid_ddos,EXPLOIT,252.13,2998,21234.723624,21442.399089,207.675465
37,qos_mid_ddos,EXPLOIT,267.13,3775,23029.182783,23290.614252,261.431469
38,qos_mid_ddos,EXPLOIT,269.13,3469,23364.176124,23604.236067,240.059943
39,qos_mid_ddos,EXPLOIT,271.13,2997,23702.760358,23910.437171,207.676813
40,qos_mid_ddos,EXPLOIT,279.13,3542,24951.666466,25197.226616,245.560150
41,nmap_10_T5,RECONNAISSANCE,281.13,42581,25272.577398,25328.753824,56.176426
42,nmap_sub,DISCOVERY,283.13,727,25389.909626,25445.093872,55.184246
43,qos_mid_ddos,EXPLOIT,286.13,2915,25488.532460,25690.368601,201.836141
44,qos_mid_ddos,EXPLOIT,290.13,3631,26053.806894,26307.044377,253.237483
45,nmap_sub,DISCOVERY,302.13,728,27812.286858,27866.679777,54.392919
46,qos_mid_ddos,EXPLOIT,304.13,3217,27905.209492,28127.830593,222.621101
47,qos_mid_ddos,EXPLOIT,312.13,3525,29055.654624,29302.752812,247.098188
48,nmap_10_T5,RECONNAISSANCE,318.13,42579,30012.213216,30068.033913,55.820697
49,nmap_sub,DISCOVERY,320.13,725,30099.626967,30153.997015,54.370048

train_dollar_char: review_required
Blockers: []

,packets,normal_packets,attack_packets,unmapped_labels,invalid_timestamps,missing_endpoints,incomplete_attack_annotations,first_timestamp_seconds,last_timestamp_seconds,duplicate_raw_rows_sha256,unique_endpoints,unique_directed_pairs
0,2882555,1705003,1177552,0,0,0,0,0.009927,46796.778032,0,160,633

               raw_label  packets
0                 normal  1705003
1            dollar_char   739943
2             nmap_10_T5   383310
3              nmap_mqtt    19736
4  brute_force_malformed    15561
5            nmap_banner    12635
6               nmap_sub     5333
7               mqtt_cat      655
8               scp_inst      379

,width_seconds,origin_offset_seconds,artifact,occupied_windows,empty_windows_between_first_and_last,mean_packets_occupied,max_packets,packet_quantiles_occupied,max_nodes,node_quantiles_occupied,max_directed_pairs,pair_quantiles_occupied,mean_packets_per_second_occupied
0,1,0.0,windows_1s_offset_0s.parquet,40000,6797,72.063875,15360,"[38.0, 168.0, 384.0]",57,"[6.0, 11.0, 13.0]",94,"[9.0, 16.0, 20.0]",72.063875
1,1,0.5,windows_1s_offset_0.5s.parquet,40000,6798,72.063875,15850,"[38.0, 168.0, 388.0200000000041]",68,"[6.0, 11.0, 13.0]",94,"[9.0, 16.0, 19.0]",72.063875
2,5,0.0,windows_5s_offset_0s.parquet,9117,243,316.173632,43211,"[189.0, 716.0, 1094.8400000000001]",85,"[13.0, 20.0, 35.0]",112,"[21.0, 32.0, 48.840000000000146]",63.234726
3,5,2.5,windows_5s_offset_2.5s.parquet,9119,241,316.104288,42436,"[189.0, 713.0, 1067.9199999999983]",79,"[13.0, 20.0, 34.0]",105,"[21.0, 32.0, 46.0]",63.220858
4,10,0.0,windows_10s_offset_0s.parquet,4680,0,615.930556,43458,"[415.0, 1354.0500000000002, 1914.5200000000004]",96,"[15.0, 24.0, 39.0]",123,"[25.0, 40.0, 69.21000000000004]",61.593056
5,10,5.0,windows_10s_offset_5s.parquet,4681,0,615.798975,43477,"[410.0, 1351.0, 1850.199999999998]",85,"[16.0, 24.0, 39.0]",112,"[25.0, 40.0, 68.0]",61.579897
6,30,0.0,windows_30s_offset_0s.parquet,1560,0,1847.791667,44273,"[1426.0, 3814.05, 5273.710000000003]",97,"[20.0, 41.0, 46.0]",170,"[34.0, 62.0, 84.41000000000008]",61.593056
7,30,15.0,windows_30s_offset_15s.parquet,1561,0,1846.607944,44876,"[1401.0, 3813.0, 4887.400000000016]",97,"[20.0, 40.0, 46.0]",131,"[33.0, 61.0, 83.0]",61.553598

,missing,numeric_values,constant_nonmissing,numeric_parse_failures_nonmissing,interpretation
layers_frame_frame.section_number,0,2882555,True,0,Parse failures may be valid categorical values...
timestamp,0,0,False,2882555,Parse failures may be valid categorical values...
layers_frame_frame.time_epoch,0,2882555,False,0,Parse failures may be valid categorical values...
layers_frame_frame.number,0,2882555,False,0,Parse failures may be valid categorical values...
layers_frame_frame.len,0,2882555,False,0,Parse failures may be valid categorical values...
...,...,...,...,...,...
phase_idx,1705003,1177552,False,0,Parse failures may be valid categorical values...
phase_name,1705003,0,False,1177552,Parse failures may be valid categorical values...
phase_number,1705003,1177552,False,0,Parse failures may be valid categorical values...
step_number,1705003,1177552,False,0,Parse failures may be valid categorical values...
sequence_id,1705003,1177552,False,0,Parse failures may be valid categorical values...

Duplicate column groups: [['layers_frame_frame.len', 'layers_frame_frame.cap_len'], ['layers_eth_eth.dst', 'layers_eth_eth.dst_tree_eth.addr'], ['layers_eth_eth.dst_tree_eth.dst_resolved', 'layers_eth_eth.dst_tree_eth.addr_resolved'], ['layers_eth_eth.dst_tree_eth.dst.oui', 'layers_eth_eth.dst_tree_eth.addr.oui'], ['layers_eth_eth.src', 'layers_eth_eth.src_tree_eth.src_resolved'], ['layers_eth_eth.src_tree_eth.src.oui', 'layers_eth_eth.src_tree_eth.addr.oui'], ['layers_ipv6_ipv6.addr', 'layers_ipv6_ipv6.host'], ['layers_ip_ip.addr', 'layers_ip_ip.host'], ['layers_tcp_tcp.dstport', 'layers_tcp_tcp.port'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_server_to_client']]

,attack_step,phase,sequence_id,packets,start_seconds,end_seconds,duration_seconds
0,nmap_10_T5,RECONNAISSANCE,3.1,42629,3361.941748,3417.969939,56.028191
1,nmap_10_T5,RECONNAISSANCE,5.1,42581,3596.558603,3653.160577,56.601974
2,nmap_10_T5,RECONNAISSANCE,9.1,42577,4156.802665,4212.535711,55.733046
3,nmap_10_T5,RECONNAISSANCE,13.1,42580,4728.300644,4784.362588,56.061944
4,mqtt_cat,DISCOVERY,36.1,91,6761.096528,6766.424700,5.328172
5,nmap_sub,DISCOVERY,38.1,760,6809.849659,6864.201538,54.351879
6,nmap_mqtt,DISCOVERY,46.1,926,7442.994004,7685.360268,242.366264
7,nmap_mqtt,DISCOVERY,58.1,965,9013.658513,9256.053345,242.394832
8,scp_inst,INSTALLATION,62.1,53,9660.634453,9660.823624,0.189171
9,scp_inst,INSTALLATION,64.1,55,9736.179490,9736.372563,0.193073
10,scp_inst,INSTALLATION,72.1,55,9957.720730,9957.914996,0.194266
11,scp_inst,INSTALLATION,74.1,53,10047.482606,10047.677836,0.195230
12,dollar_char,EXPLOIT,76.1,3119,10080.939893,10118.967668,38.027775
13,dollar_char,EXPLOIT,82.1,5376,10427.774340,10495.094551,67.320211
14,dollar_char,EXPLOIT,84.1,4687,10539.557644,10598.144232,58.586588
15,dollar_char,EXPLOIT,86.1,3688,10649.843158,10695.803185,45.960027
16,dollar_char,EXPLOIT,88.1,4138,10779.650622,10831.723596,52.072974
17,nmap_mqtt,DISCOVERY,98.1,982,11547.003135,11789.391268,242.388133
18,dollar_char,EXPLOIT,118.1,4631,12872.154566,12929.344236,57.189670
19,dollar_char,EXPLOIT,122.1,4215,13088.855039,13141.329716,52.474677
20,dollar_char,EXPLOIT,130.1,3516,13937.595069,13980.466105,42.871036
21,dollar_char,EXPLOIT,140.1,4825,14514.857879,14574.619503,59.761624
22,dollar_char,EXPLOIT,142.1,3134,14611.753263,14651.758222,40.004959
23,dollar_char,EXPLOIT,148.1,3264,14990.700198,15029.581130,38.880932
24,nmap_mqtt,DISCOVERY,150.1,926,15274.917827,15517.295718,242.377891
25,dollar_char,EXPLOIT,170.1,3062,16570.619362,16609.249264,38.629902
26,nmap_mqtt,DISCOVERY,176.1,921,17039.341316,17281.747864,242.406548
27,nmap_banner,DISCOVERY,178.1,901,17322.481592,17386.851176,64.369584
28,nmap_10_T5,RECONNAISSANCE,194.1,42572,18455.896854,18511.779176,55.882322
29,dollar_char,EXPLOIT,200.1,4722,18914.824773,18973.388047,58.563274
30,nmap_mqtt,DISCOVERY,208.1,972,19522.287388,19764.705456,242.418068
31,nmap_banner,DISCOVERY,210.1,900,19858.299281,19922.633995,64.334714
32,dollar_char,EXPLOIT,220.1,5482,20483.180310,20550.943639,67.763329
33,dollar_char,EXPLOIT,230.1,3711,21135.179150,21181.232224,46.053074
34,dollar_char,EXPLOIT,240.1,4311,22056.423258,22109.951224,53.527966
35,dollar_char,EXPLOIT,242.1,4865,22202.703234,22263.991614,61.288380
36,dollar_char,EXPLOIT,268.1,3192,24053.452107,24093.267622,39.815515
37,dollar_char,EXPLOIT,272.1,3951,24265.019292,24313.541808,48.522516
38,dollar_char,EXPLOIT,278.1,2958,24589.029303,24626.436568,37.407265
39,dollar_char,EXPLOIT,280.1,5162,24694.458948,24759.659185,65.200237
40,dollar_char,EXPLOIT,282.1,5980,24858.033389,24932.393876,74.360487
41,dollar_char,EXPLOIT,291.1,2488,25696.279400,25727.443539,31.164139
42,dollar_char,EXPLOIT,295.1,3381,25917.394002,25959.481429,42.087427
43,dollar_char,EXPLOIT,297.1,5044,26031.772723,26096.007144,64.234421
44,dollar_char,EXPLOIT,299.1,4933,26158.510595,26219.842931,61.332336
45,dollar_char,EXPLOIT,303.1,3371,26422.224966,26464.020852,41.795886
46,nmap_mqtt,DISCOVERY,313.1,920,27140.411168,27382.812056,242.400888
47,dollar_char,EXPLOIT,319.1,5521,27689.903965,27758.982843,69.078878
48,dollar_char,EXPLOIT,323.1,4068,27928.066998,27979.254647,51.187649
49,dollar_char,EXPLOIT,325.1,3689,28037.537839,28081.462839,43.925000

train_slash_char: review_required
Blockers: []

,packets,normal_packets,attack_packets,unmapped_labels,invalid_timestamps,missing_endpoints,incomplete_attack_annotations,first_timestamp_seconds,last_timestamp_seconds,duplicate_raw_rows_sha256,unique_endpoints,unique_directed_pairs
0,6425516,1705003,4720513,0,0,0,0,0.009927,46796.778032,0,164,435

            raw_label  packets
0          nmap_10_T4  4087537
1              normal  1705003
2          slash_char   389562
3          nmap_10_T5   127814
4  brute_force_timing   107510
5           nmap_mqtt     2839
6         nmap_banner     2728
7            nmap_sub     2190
8            mqtt_cat      282
9           sftp_inst       51

,width_seconds,origin_offset_seconds,artifact,occupied_windows,empty_windows_between_first_and_last,mean_packets_occupied,max_packets,packet_quantiles_occupied,max_nodes,node_quantiles_occupied,max_directed_pairs,pair_quantiles_occupied,mean_packets_per_second_occupied
0,1,0.0,windows_1s_offset_0s.parquet,39709,7088,161.815105,15827,"[33.0, 186.0, 1071.5199999999895]",57,"[6.0, 10.0, 26.0]",94,"[8.0, 15.0, 44.0]",161.815105
1,1,0.5,windows_1s_offset_0.5s.parquet,39699,7099,161.855865,15778,"[33.0, 191.0, 1111.2799999999552]",68,"[6.0, 10.0, 26.0]",94,"[8.0, 15.0, 44.0]",161.855865
2,5,0.0,windows_5s_offset_0s.parquet,9117,243,704.784030,42517,"[176.0, 768.9999999999945, 24660.920000000286]",85,"[13.0, 20.0, 36.0]",112,"[21.0, 32.0, 64.0]",140.956806
3,5,2.5,windows_5s_offset_2.5s.parquet,9120,240,704.552193,42707,"[176.0, 760.0499999999993, 23888.469999999954]",79,"[13.0, 20.0, 36.0]",105,"[21.0, 32.0, 63.0]",140.910439
4,10,0.0,windows_10s_offset_0s.parquet,4680,0,1372.973504,43873,"[387.5, 1466.0500000000002, 42302.259999999995]",96,"[15.0, 35.0, 39.0]",123,"[25.0, 46.0, 70.21000000000004]",137.297350
5,10,5.0,windows_10s_offset_5s.parquet,4681,0,1372.680197,42914,"[390.0, 1441.0, 42350.600000000006]",85,"[15.0, 35.0, 39.0]",112,"[25.0, 45.0, 70.0]",137.268020
6,30,0.0,windows_30s_offset_0s.parquet,1560,0,4118.920513,44986,"[1461.0, 42763.049999999996, 43653.07]",97,"[20.0, 42.0, 46.0]",170,"[34.0, 74.0, 85.41000000000008]",137.297350
7,30,15.0,windows_30s_offset_15s.parquet,1561,0,4116.281871,44828,"[1456.0, 42720.0, 43491.8]",97,"[20.0, 42.0, 46.0]",131,"[34.0, 74.0, 84.0]",137.209396

,missing,numeric_values,constant_nonmissing,numeric_parse_failures_nonmissing,interpretation
layers_frame_frame.section_number,0,6425516,True,0,Parse failures may be valid categorical values...
timestamp,0,0,False,6425516,Parse failures may be valid categorical values...
layers_frame_frame.time_epoch,0,6425516,False,0,Parse failures may be valid categorical values...
layers_frame_frame.number,0,6425516,False,0,Parse failures may be valid categorical values...
layers_frame_frame.len,0,6425516,False,0,Parse failures may be valid categorical values...
...,...,...,...,...,...
phase_idx,1705003,4720513,False,0,Parse failures may be valid categorical values...
phase_name,1705003,0,False,4720513,Parse failures may be valid categorical values...
phase_number,1705003,4720513,False,0,Parse failures may be valid categorical values...
step_number,1705003,4720513,False,0,Parse failures may be valid categorical values...
sequence_id,1705003,4720513,False,0,Parse failures may be valid categorical values...

Duplicate column groups: [['layers_frame_frame.len', 'layers_frame_frame.cap_len'], ['layers_eth_eth.dst', 'layers_eth_eth.dst_tree_eth.addr'], ['layers_eth_eth.dst_tree_eth.dst_resolved', 'layers_eth_eth.dst_tree_eth.addr_resolved'], ['layers_eth_eth.dst_tree_eth.dst.oui', 'layers_eth_eth.dst_tree_eth.addr.oui'], ['layers_eth_eth.src', 'layers_eth_eth.src_tree_eth.src_resolved'], ['layers_eth_eth.src_tree_eth.src.oui', 'layers_eth_eth.src_tree_eth.addr.oui'], ['layers_ipv6_ipv6.addr', 'layers_ipv6_ipv6.host'], ['layers_ip_ip.addr', 'layers_ip_ip.host'], ['layers_tcp_tcp.dstport', 'layers_tcp_tcp.port'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_server_to_client']]

,attack_step,phase,sequence_id,packets,start_seconds,end_seconds,duration_seconds
0,nmap_10_T5,RECONNAISSANCE,2.14,42632,3370.159780,3426.984987,56.825207
1,nmap_10_T5,RECONNAISSANCE,4.14,42579,3474.438453,3530.660114,56.221661
2,nmap_10_T5,RECONNAISSANCE,6.14,42603,3595.953615,3652.184782,56.231167
3,brute_force_timing,BRUTE_FORCE,8.14,107510,3703.395347,4751.270530,1047.875183
4,nmap_mqtt,DISCOVERY,10.14,971,4806.838095,5049.224297,242.386202
5,mqtt_cat,DISCOVERY,14.14,95,5226.888633,5232.106602,5.217969
6,nmap_sub,DISCOVERY,16.14,732,5312.478393,5367.612193,55.133800
7,nmap_mqtt,DISCOVERY,27.14,932,6191.165058,6433.582635,242.417577
8,slash_char,EXPLOIT,39.14,3600,6977.213219,7021.544529,44.331310
9,slash_char,EXPLOIT,43.14,1022,7151.065388,7164.449684,13.384296
10,slash_char,EXPLOIT,51.14,1236,7546.262703,7561.343941,15.081238
11,nmap_10_T4,RECONNAISSANCE,67.14,42583,8086.410058,8142.845846,56.435788
12,slash_char,EXPLOIT,70.14,1829,8195.325038,8218.775576,23.450538
13,slash_char,EXPLOIT,73.14,1764,8287.027518,8308.497602,21.470084
14,nmap_10_T4,RECONNAISSANCE,81.14,42579,8497.626995,8554.408564,56.781569
15,nmap_10_T4,RECONNAISSANCE,86.14,42583,8673.528398,8730.172052,56.643654
16,nmap_10_T4,RECONNAISSANCE,102.14,42575,9329.369815,9386.036406,56.666591
17,slash_char,EXPLOIT,109.14,613,9684.156613,9691.978589,7.821976
18,nmap_10_T4,RECONNAISSANCE,117.14,42577,10102.808792,10159.398342,56.589550
19,slash_char,EXPLOIT,119.14,1193,10207.271907,10223.419992,16.148085
20,slash_char,EXPLOIT,135.14,1048,10777.518008,10790.332493,12.814485
21,nmap_10_T4,RECONNAISSANCE,150.14,42578,11365.574314,11422.207376,56.633062
22,slash_char,EXPLOIT,152.14,1378,11477.372735,11494.723984,17.351249
23,slash_char,EXPLOIT,154.14,197,11534.489233,11536.377592,1.888359
24,slash_char,EXPLOIT,156.14,1494,11610.197287,11628.208747,18.011460
25,slash_char,EXPLOIT,158.14,2469,11713.478471,11745.148258,31.669787
26,nmap_10_T4,RECONNAISSANCE,160.14,42578,11788.533379,11845.048648,56.515269
27,slash_char,EXPLOIT,173.14,1999,12248.796736,12273.871439,25.074703
28,nmap_10_T4,RECONNAISSANCE,175.14,42581,12347.067406,12403.749957,56.682551
29,slash_char,EXPLOIT,177.14,2449,12447.221224,12478.138767,30.917543
30,slash_char,EXPLOIT,185.14,3573,12756.575893,12801.770907,45.195014
31,nmap_10_T4,RECONNAISSANCE,191.14,42567,12975.686791,13032.245677,56.558886
32,slash_char,EXPLOIT,201.14,197,13365.885105,13367.716527,1.831422
33,slash_char,EXPLOIT,204.14,1100,13430.405703,13443.751606,13.345903
34,nmap_10_T4,RECONNAISSANCE,208.14,42573,13535.642976,13592.286888,56.643912
35,nmap_10_T4,RECONNAISSANCE,213.14,42577,13749.191384,13805.546248,56.354864
36,nmap_10_T4,RECONNAISSANCE,225.14,42567,14176.433358,14232.916776,56.483418
37,slash_char,EXPLOIT,255.14,991,15520.656558,15532.717566,12.061008
38,nmap_10_T4,RECONNAISSANCE,257.14,42579,15612.917346,15669.382153,56.464807
39,slash_char,EXPLOIT,259.14,1522,15726.852105,15746.319622,19.467517
40,slash_char,EXPLOIT,264.14,1967,15902.356028,15925.959690,23.603662
41,nmap_10_T4,RECONNAISSANCE,278.14,42579,16524.869302,16581.350953,56.481651
42,nmap_10_T4,RECONNAISSANCE,290.14,42576,17058.503342,17115.146184,56.642842
43,nmap_10_T4,RECONNAISSANCE,294.14,42577,17266.592768,17323.342184,56.749416
44,slash_char,EXPLOIT,300.14,687,17461.053089,17469.453599,8.400510
45,slash_char,EXPLOIT,302.14,2454,17519.198089,17549.566745,30.368656
46,slash_char,EXPLOIT,305.14,1258,17626.177916,17642.169578,15.991662
47,nmap_10_T4,RECONNAISSANCE,307.14,42581,17677.440785,17734.155274,56.714489
48,nmap_10_T4,RECONNAISSANCE,312.14,42579,17852.195371,17909.120485,56.925114
49,slash_char,EXPLOIT,315.14,883,17948.591158,17959.144730,10.553572

train_sub_exf: review_required
Blockers: []

,packets,normal_packets,attack_packets,unmapped_labels,invalid_timestamps,missing_endpoints,incomplete_attack_annotations,first_timestamp_seconds,last_timestamp_seconds,duplicate_raw_rows_sha256,unique_endpoints,unique_directed_pairs
0,2225807,1705003,520804,0,0,0,0,0.009927,46796.778032,0,121,497

            raw_label  packets
0              normal  1705003
1          nmap_10_T5   255580
2  brute_force_timing   107640
3         nmap_banner    79052
4            nmap_sub    67366
5             scp_exf     5764
6           nmap_mqtt     2852
7            mqtt_cat     2550

,width_seconds,origin_offset_seconds,artifact,occupied_windows,empty_windows_between_first_and_last,mean_packets_occupied,max_packets,packet_quantiles_occupied,max_nodes,node_quantiles_occupied,max_directed_pairs,pair_quantiles_occupied,mean_packets_per_second_occupied
0,1,0.0,windows_1s_offset_0s.parquet,39538,7259,56.295387,15427,"[30.0, 165.15000000000146, 458.0]",57,"[5.0, 9.0, 25.0]",94,"[8.0, 14.0, 30.0]",56.295387
1,1,0.5,windows_1s_offset_0.5s.parquet,39547,7251,56.282575,16135,"[30.0, 167.0, 450.0]",68,"[5.0, 9.0, 26.0]",94,"[8.0, 14.0, 30.0]",56.282575
2,5,0.0,windows_5s_offset_0s.parquet,9116,244,244.164875,42250,"[165.0, 620.0, 1103.0000000000073]",85,"[13.0, 32.0, 37.0]",112,"[21.0, 41.0, 66.0]",48.832975
3,5,2.5,windows_5s_offset_2.5s.parquet,9118,242,244.111318,42326,"[166.0, 605.2999999999993, 1045.3199999999997]",79,"[13.0, 31.149999999999636, 37.0]",105,"[21.0, 40.149999999999636, 66.0]",48.822264
4,10,0.0,windows_10s_offset_0s.parquet,4680,0,475.599786,42685,"[357.0, 1028.1500000000005, 1749.21]",96,"[15.0, 37.0, 40.0]",123,"[25.0, 58.05000000000018, 72.0]",47.559979
5,10,5.0,windows_10s_offset_5s.parquet,4681,0,475.498184,42804,"[358.0, 1025.0, 1641.3999999999996]",85,"[15.0, 37.0, 40.0]",112,"[25.0, 57.0, 74.0]",47.549818
6,30,0.0,windows_30s_offset_0s.parquet,1560,0,1426.799359,43793,"[1276.5, 2524.45, 3936.1300000000074]",97,"[20.0, 43.0, 51.0]",170,"[33.0, 78.0, 84.0]",47.559979
7,30,15.0,windows_30s_offset_15s.parquet,1561,0,1425.885330,43900,"[1264.0, 2498.0, 3988.4000000000087]",97,"[20.0, 42.0, 51.0]",131,"[34.0, 78.0, 84.40000000000009]",47.529511

,missing,numeric_values,constant_nonmissing,numeric_parse_failures_nonmissing,interpretation
layers_frame_frame.section_number,0,2225807,True,0,Parse failures may be valid categorical values...
timestamp,0,0,False,2225807,Parse failures may be valid categorical values...
layers_frame_frame.time_epoch,0,2225807,False,0,Parse failures may be valid categorical values...
layers_frame_frame.number,0,2225807,False,0,Parse failures may be valid categorical values...
layers_frame_frame.len,0,2225807,False,0,Parse failures may be valid categorical values...
...,...,...,...,...,...
phase_idx,1705003,520804,False,0,Parse failures may be valid categorical values...
phase_name,1705003,0,False,520804,Parse failures may be valid categorical values...
phase_number,1705003,520804,False,0,Parse failures may be valid categorical values...
step_number,1705003,520804,False,0,Parse failures may be valid categorical values...
sequence_id,1705003,520804,False,0,Parse failures may be valid categorical values...

Duplicate column groups: [['layers_frame_frame.len', 'layers_frame_frame.cap_len'], ['layers_eth_eth.dst', 'layers_eth_eth.dst_tree_eth.addr'], ['layers_eth_eth.dst_tree_eth.dst_resolved', 'layers_eth_eth.dst_tree_eth.addr_resolved'], ['layers_eth_eth.dst_tree_eth.dst.oui', 'layers_eth_eth.dst_tree_eth.addr.oui'], ['layers_eth_eth.src', 'layers_eth_eth.src_tree_eth.src_resolved'], ['layers_eth_eth.src_tree_eth.src.oui', 'layers_eth_eth.src_tree_eth.addr.oui'], ['layers_ipv6_ipv6.addr', 'layers_ipv6_ipv6.host'], ['layers_ip_ip.addr', 'layers_ip_ip.host'], ['layers_tcp_tcp.dstport', 'layers_tcp_tcp.port'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.encryption_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.mac_algorithms_server_to_client'], ['layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_client_to_server', 'layers_ssh_SSH Version 2_Key Exchange_Algorithms_ssh.compression_algorithms_server_to_client']]

,attack_step,phase,sequence_id,packets,start_seconds,end_seconds,duration_seconds
0,nmap_10_T5,RECONNAISSANCE,2.15,42666,3171.125405,3226.938418,55.813013
1,nmap_10_T5,RECONNAISSANCE,4.15,42579,3290.338422,3346.309933,55.971511
2,nmap_10_T5,RECONNAISSANCE,6.15,42596,3405.306401,3461.190726,55.884325
3,nmap_10_T5,RECONNAISSANCE,8.15,42583,3497.126019,3553.553107,56.427088
4,nmap_10_T5,RECONNAISSANCE,10.15,42579,3618.369427,3674.331933,55.962506
5,nmap_10_T5,RECONNAISSANCE,12.15,42577,3704.979033,3760.717752,55.738719
6,brute_force_timing,BRUTE_FORCE,14.15,107640,3807.653315,4868.518765,1060.865450
7,mqtt_cat,DISCOVERY,44.15,91,6893.618145,6898.840303,5.222158
8,scp_exf,EXPLOIT,46.15,49,6956.763423,6956.947811,0.184388
9,nmap_sub,DISCOVERY,52.15,726,7258.745333,7313.121387,54.376054
10,nmap_banner,DISCOVERY,80.15,896,8640.423922,8705.164036,64.740114
11,nmap_sub,DISCOVERY,82.15,716,8790.015324,8844.424395,54.409071
12,scp_exf,EXPLOIT,84.15,49,8929.682715,8929.863948,0.181233
13,nmap_banner,DISCOVERY,100.15,898,9760.497042,9824.870876,64.373834
14,nmap_sub,DISCOVERY,104.15,724,9990.823863,10045.198365,54.374502
15,scp_exf,EXPLOIT,106.15,49,10116.014912,10116.194525,0.179613
16,nmap_banner,DISCOVERY,108.15,894,10214.246962,10278.585010,64.338048
17,mqtt_cat,DISCOVERY,118.15,93,10745.974932,10751.235364,5.260432
18,nmap_sub,DISCOVERY,126.15,724,11155.971454,11210.355453,54.383999
19,scp_exf,EXPLOIT,136.15,48,11735.687908,11735.873438,0.185530
20,nmap_banner,DISCOVERY,138.15,892,11785.182401,11849.517742,64.335341
21,nmap_sub,DISCOVERY,142.15,726,11973.221049,12027.611436,54.390387
22,mqtt_cat,DISCOVERY,166.15,102,13171.074660,13177.019407,5.944747
23,nmap_banner,DISCOVERY,171.15,895,13514.752959,13579.066451,64.313492
24,mqtt_cat,DISCOVERY,175.15,91,13766.677256,13771.896301,5.219045
25,scp_exf,EXPLOIT,177.15,51,13804.540625,13804.724316,0.183691
26,nmap_sub,DISCOVERY,185.15,727,14089.666509,14144.024195,54.357686
27,scp_exf,EXPLOIT,199.15,48,14802.455215,14802.636957,0.181742
28,scp_exf,EXPLOIT,216.15,49,15730.429815,15730.609364,0.179549
29,nmap_banner,DISCOVERY,218.15,912,15763.161134,15827.508908,64.347774
30,nmap_sub,DISCOVERY,220.15,724,15861.435878,15915.818282,54.382404
31,nmap_banner,DISCOVERY,246.15,896,17060.969952,17125.296159,64.326207
32,nmap_sub,DISCOVERY,254.15,722,17466.626139,17520.998244,54.372105
33,scp_exf,EXPLOIT,262.15,49,17859.432504,17859.618879,0.186375
34,nmap_sub,DISCOVERY,274.15,726,18378.587948,18432.954368,54.366420
35,scp_exf,EXPLOIT,282.15,49,18817.395275,18817.581718,0.186443
36,nmap_banner,DISCOVERY,284.15,897,18853.570838,18917.913357,64.342519
37,scp_exf,EXPLOIT,300.15,51,19616.632443,19616.817812,0.185369
38,nmap_banner,DISCOVERY,302.15,890,19711.931069,19776.259191,64.328122
39,nmap_sub,DISCOVERY,304.15,728,19821.438047,19875.817381,54.379334
40,scp_exf,EXPLOIT,306.15,49,19935.437972,19935.621881,0.183909
41,nmap_banner,DISCOVERY,332.15,901,21302.125469,21366.460899,64.335430
42,nmap_sub,DISCOVERY,334.15,734,21415.882157,21470.263369,54.381212
43,scp_exf,EXPLOIT,335.15,52,21471.126247,21471.309348,0.183101
44,nmap_sub,DISCOVERY,349.15,714,22137.160368,22191.527375,54.367007
45,scp_exf,EXPLOIT,351.15,49,22243.026106,22243.209717,0.183611
46,nmap_sub,DISCOVERY,355.15,724,22457.711548,22512.065381,54.353833
47,scp_exf,EXPLOIT,357.15,49,22548.864402,22549.047368,0.182966
48,nmap_banner,DISCOVERY,375.15,892,23444.723816,23509.035305,64.311489
49,nmap_sub,DISCOVERY,377.15,711,23575.980523,23630.373404,54.392881

In [ ]:
scenario_summary = []
window_summary = []
label_summary = []
column_sets = {}

for scenario, report in REPORTS.items():
    counts = report["counts"]
    column_sets[scenario] = set(report["column_profiles"])

    scenario_summary.append({
        "scenario": scenario,
        "status": report["status"],
        "blockers": ", ".join(report["blockers"]),
        "packets": counts["packets"],
        "normal_packets": counts["normal_packets"],
        "attack_packets": counts["attack_packets"],
        "attack_fraction": (
            counts["attack_packets"] / counts["packets"]
        ),
        "unique_endpoints": counts["unique_endpoints"],
        "unique_directed_pairs": counts["unique_directed_pairs"],
        "invalid_timestamps": counts["invalid_timestamps"],
        "timestamp_inversions": report["timestamp_order_inversions"],
        "unmapped_labels": counts["unmapped_labels"],
        "missing_endpoints": counts["missing_endpoints"],
        "incomplete_attack_annotations": (
            counts["incomplete_attack_annotations"]
        ),
        "duplicate_raw_rows": counts["duplicate_raw_rows_sha256"],
        "source_gib": report["source_size_bytes"] / 1024**3,
        "audit_parquet_gib": (
            report["audit_parquet_size_bytes"] / 1024**3
        ),
        "columns": len(report["column_profiles"]),
        "duplicate_column_groups": len(
            report["duplicate_column_groups_sha256"]
        ),
    })

    for item in report["raw_labels"]:
        label_summary.append({
            "scenario": scenario,
            **item,
        })

    for item in report["windows"]:
        window_summary.append({
            "scenario": scenario,
            "width_seconds": item["width_seconds"],
            "origin_offset_seconds": item["origin_offset_seconds"],
            "occupied_windows": item["occupied_windows"],
            "empty_windows": (
                item["empty_windows_between_first_and_last"]
            ),
            "median_packets": item["packet_quantiles_occupied"][0],
            "p95_packets": item["packet_quantiles_occupied"][1],
            "p99_packets": item["packet_quantiles_occupied"][2],
            "max_packets": item["max_packets"],
            "p99_nodes": item["node_quantiles_occupied"][2],
            "max_nodes": item["max_nodes"],
            "p99_directed_pairs": item[
                "pair_quantiles_occupied"
            ][2],
            "max_directed_pairs": item["max_directed_pairs"],
        })

scenario_summary = pd.DataFrame(scenario_summary)
label_summary = pd.DataFrame(label_summary)
window_summary = pd.DataFrame(window_summary)

all_columns = set.union(*column_sets.values())
common_columns = set.intersection(*column_sets.values())

schema_differences = {
    scenario: {
        "missing_from_union": sorted(all_columns - columns),
        "scenario_specific": sorted(
            columns - set.union(
                *[
                    other_columns
                    for other_scenario, other_columns
                    in column_sets.items()
                    if other_scenario != scenario
                ]
            )
        ),
    }
    for scenario, columns in column_sets.items()
}

iteration_summaries = []

for scenario, result in RESULTS.items():
    artifact_directory = Path(result["report"]).parent
    iterations = pd.read_parquet(
        artifact_directory / "attack_iterations.parquet"
    )

    sequence_cardinality = iterations.groupby("sequence_id").agg(
        attack_steps=("attack_step", "nunique"),
        phases=("phase", "nunique"),
    )
    conflicts = sequence_cardinality[
        (sequence_cardinality["attack_steps"] > 1)
        | (sequence_cardinality["phases"] > 1)
    ]

    by_step = (
        iterations.groupby(["attack_step", "phase"], as_index=False)
        .agg(
            iterations=("sequence_id", "nunique"),
            packets=("packets", "sum"),
            min_duration_seconds=("duration_seconds", "min"),
            median_duration_seconds=("duration_seconds", "median"),
            max_duration_seconds=("duration_seconds", "max"),
        )
    )
    by_step.insert(0, "scenario", scenario)
    by_step["sequence_conflicts"] = len(conflicts)
    iteration_summaries.append(by_step)

attack_step_summary = pd.concat(
    iteration_summaries,
    ignore_index=True,
)

print("Scenario summary")
display(scenario_summary)

print("Raw label summary")
display(label_summary)

print("Window summary")
display(window_summary)

print(f"Union columns: {len(all_columns)}")
print(f"Common columns: {len(common_columns)}")
print("Schema differences")
print(json.dumps(schema_differences, indent=2))

print("Attack-step summary")
display(attack_step_summary)

Scenario summary

,scenario,status,blockers,packets,normal_packets,attack_packets,attack_fraction,unique_endpoints,unique_directed_pairs,invalid_timestamps,timestamp_inversions,unmapped_labels,missing_endpoints,incomplete_attack_annotations,duplicate_raw_rows,source_gib,audit_parquet_gib,columns,duplicate_column_groups
0,train_empty_conn,review_required,,1175779,746806,428973,0.364842,160,623,0,0,0,0,0,0,0.960427,0.248701,108,12
1,train_qos_mid,review_required,,1499717,746806,752911,0.502035,163,481,0,0,0,0,0,0,0.969574,0.198402,107,12
2,train_dollar_char,review_required,,2882555,1705003,1177552,0.408510,160,633,0,0,0,0,0,0,1.833687,0.375520,107,12
3,train_slash_char,review_required,,6425516,1705003,4720513,0.734651,164,435,0,0,0,0,0,0,4.745214,0.698431,108,12
4,train_sub_exf,review_required,,2225807,1705003,520804,0.233984,121,497,0,0,0,0,0,0,1.545524,0.356730,107,12

Raw label summary

             scenario              raw_label  packets
0    train_empty_conn                 normal   746806
1    train_empty_conn             nmap_10_T4   255667
2    train_empty_conn     brute_force_timing   107515
3    train_empty_conn        empty_conn_ddos    28269
4    train_empty_conn              nmap_mqtt    14168
5    train_empty_conn            nmap_banner    12649
6    train_empty_conn             empty_conn     6650
7    train_empty_conn               nmap_sub     2277
8    train_empty_conn               mqtt_cat     1171
9    train_empty_conn              sftp_inst      607
10      train_qos_mid                 normal   746806
11      train_qos_mid             nmap_10_T5   425805
12      train_qos_mid           qos_mid_ddos   257148
13      train_qos_mid  brute_force_malformed    30860
14      train_qos_mid                qos_mid    12477
15      train_qos_mid               nmap_sub     8753
16      train_qos_mid              nmap_mqtt     8458
17      train_qos_mid            nmap_banner     8188
18      train_qos_mid               mqtt_cat      955
19      train_qos_mid               scp_inst      267
20  train_dollar_char                 normal  1705003
21  train_dollar_char            dollar_char   739943
22  train_dollar_char             nmap_10_T5   383310
23  train_dollar_char              nmap_mqtt    19736
24  train_dollar_char  brute_force_malformed    15561
25  train_dollar_char            nmap_banner    12635
26  train_dollar_char               nmap_sub     5333
27  train_dollar_char               mqtt_cat      655
28  train_dollar_char               scp_inst      379
29   train_slash_char             nmap_10_T4  4087537
30   train_slash_char                 normal  1705003
31   train_slash_char             slash_char   389562
32   train_slash_char             nmap_10_T5   127814
33   train_slash_char     brute_force_timing   107510
34   train_slash_char              nmap_mqtt     2839
35   train_slash_char            nmap_banner     2728
36   train_slash_char               nmap_sub     2190
37   train_slash_char               mqtt_cat      282
38   train_slash_char              sftp_inst       51
39      train_sub_exf                 normal  1705003
40      train_sub_exf             nmap_10_T5   255580
41      train_sub_exf     brute_force_timing   107640
42      train_sub_exf            nmap_banner    79052
43      train_sub_exf               nmap_sub    67366
44      train_sub_exf                scp_exf     5764
45      train_sub_exf              nmap_mqtt     2852
46      train_sub_exf               mqtt_cat     2550

Window summary

,scenario,width_seconds,origin_offset_seconds,occupied_windows,empty_windows,median_packets,p95_packets,p99_packets,max_packets,p99_nodes,max_nodes,p99_directed_pairs,max_directed_pairs
0,train_empty_conn,1,0.0,44480,2320,16.0,37.00,145.42,15524,10.0,56,14.00,96
1,train_empty_conn,1,0.5,44435,2366,16.0,37.00,146.00,15616,11.0,67,14.66,92
2,train_empty_conn,5,0.0,9360,0,79.0,134.05,616.41,42145,33.0,86,40.41,108
3,train_empty_conn,5,2.5,9361,0,79.0,132.00,616.20,42148,33.0,80,40.00,106
4,train_empty_conn,10,0.0,4680,0,159.0,261.10,920.00,42245,37.0,88,62.00,111
5,train_empty_conn,10,5.0,4681,0,161.0,267.00,874.20,42231,37.0,86,60.20,115
6,train_empty_conn,30,0.0,1560,0,490.5,1032.10,1678.44,42592,45.0,95,74.23,162
7,train_empty_conn,30,15.0,1561,0,492.0,1027.00,1633.00,43255,45.4,93,77.00,132
8,train_qos_mid,1,0.0,45154,1646,21.0,45.00,75.00,14815,11.0,56,16.00,96
9,train_qos_mid,1,0.5,45107,1694,21.0,45.00,75.00,14642,11.0,67,16.00,92
10,train_qos_mid,5,0.0,9360,0,99.0,183.00,612.00,42191,32.0,86,41.00,108
11,train_qos_mid,5,2.5,9361,0,99.0,183.00,614.40,42125,32.0,80,41.00,106
12,train_qos_mid,10,0.0,4680,0,197.0,354.05,826.00,42322,36.0,88,60.00,111
13,train_qos_mid,10,5.0,4681,0,198.0,362.00,826.00,42891,36.2,86,60.00,115
14,train_qos_mid,30,0.0,1560,0,638.5,1104.15,2001.47,43222,45.0,95,74.41,162
15,train_qos_mid,30,15.0,1561,0,632.0,1067.00,2038.60,43284,45.0,93,76.00,132
16,train_dollar_char,1,0.0,40000,6797,38.0,168.00,384.00,15360,13.0,57,20.00,94
17,train_dollar_char,1,0.5,40000,6798,38.0,168.00,388.02,15850,13.0,68,19.00,94
18,train_dollar_char,5,0.0,9117,243,189.0,716.00,1094.84,43211,35.0,85,48.84,112
19,train_dollar_char,5,2.5,9119,241,189.0,713.00,1067.92,42436,34.0,79,46.00,105
20,train_dollar_char,10,0.0,4680,0,415.0,1354.05,1914.52,43458,39.0,96,69.21,123
21,train_dollar_char,10,5.0,4681,0,410.0,1351.00,1850.20,43477,39.0,85,68.00,112
22,train_dollar_char,30,0.0,1560,0,1426.0,3814.05,5273.71,44273,46.0,97,84.41,170
23,train_dollar_char,30,15.0,1561,0,1401.0,3813.00,4887.40,44876,46.0,97,83.00,131
24,train_slash_char,1,0.0,39709,7088,33.0,186.00,1071.52,15827,26.0,57,44.00,94
25,train_slash_char,1,0.5,39699,7099,33.0,191.00,1111.28,15778,26.0,68,44.00,94
26,train_slash_char,5,0.0,9117,243,176.0,769.00,24660.92,42517,36.0,85,64.00,112
27,train_slash_char,5,2.5,9120,240,176.0,760.05,23888.47,42707,36.0,79,63.00,105
28,train_slash_char,10,0.0,4680,0,387.5,1466.05,42302.26,43873,39.0,96,70.21,123
29,train_slash_char,10,5.0,4681,0,390.0,1441.00,42350.60,42914,39.0,85,70.00,112
30,train_slash_char,30,0.0,1560,0,1461.0,42763.05,43653.07,44986,46.0,97,85.41,170
31,train_slash_char,30,15.0,1561,0,1456.0,42720.00,43491.80,44828,46.0,97,84.00,131
32,train_sub_exf,1,0.0,39538,7259,30.0,165.15,458.00,15427,25.0,57,30.00,94
33,train_sub_exf,1,0.5,39547,7251,30.0,167.00,450.00,16135,26.0,68,30.00,94
34,train_sub_exf,5,0.0,9116,244,165.0,620.00,1103.00,42250,37.0,85,66.00,112
35,train_sub_exf,5,2.5,9118,242,166.0,605.30,1045.32,42326,37.0,79,66.00,105
36,train_sub_exf,10,0.0,4680,0,357.0,1028.15,1749.21,42685,40.0,96,72.00,123
37,train_sub_exf,10,5.0,4681,0,358.0,1025.00,1641.40,42804,40.0,85,74.00,112
38,train_sub_exf,30,0.0,1560,0,1276.5,2524.45,3936.13,43793,51.0,97,84.00,170
39,train_sub_exf,30,15.0,1561,0,1264.0,2498.00,3988.40,43900,51.0,97,84.40,131

Union columns: 108
Common columns: 107
Schema differences
{
  "train_empty_conn": {
    "missing_from_union": [],
    "scenario_specific": []
  },
  "train_qos_mid": {
    "missing_from_union": [
      "layers_tcp_tcp.options_tree_tcp.options.sack"
    ],
    "scenario_specific": []
  },
  "train_dollar_char": {
    "missing_from_union": [
      "layers_tcp_tcp.options_tree_tcp.options.sack"
    ],
    "scenario_specific": []
  },
  "train_slash_char": {
    "missing_from_union": [],
    "scenario_specific": []
  },
  "train_sub_exf": {
    "missing_from_union": [
      "layers_tcp_tcp.options_tree_tcp.options.sack"
    ],
    "scenario_specific": []
  }
}
Attack-step summary

,scenario,attack_step,phase,iterations,packets,min_duration_seconds,median_duration_seconds,max_duration_seconds,sequence_conflicts
0,train_empty_conn,brute_force_timing,BRUTE_FORCE,1,107515,1048.432440,1048.432440,1048.432440,0
1,train_empty_conn,empty_conn,EXPLOIT,37,6650,76.621535,95.356958,114.146406,0
2,train_empty_conn,empty_conn_ddos,EXPLOIT,7,28269,2394.303065,2450.593708,2464.030255,0
3,train_empty_conn,mqtt_cat,DISCOVERY,12,1171,5.206165,5.223312,5.789674,0
4,train_empty_conn,nmap_10_T4,RECONNAISSANCE,6,255667,56.092985,56.684457,56.845175,0
5,train_empty_conn,nmap_banner,DISCOVERY,14,12649,64.334165,64.359124,65.149329,0
6,train_empty_conn,nmap_mqtt,DISCOVERY,15,14168,242.378472,242.401024,242.453249,0
7,train_empty_conn,nmap_sub,DISCOVERY,3,2277,54.377392,54.386559,54.397186,0
8,train_empty_conn,sftp_inst,INSTALLATION,12,607,0.153654,0.164405,0.168971,0
9,train_qos_mid,brute_force_malformed,BRUTE_FORCE,2,30860,860.257237,876.992471,893.727705,0
10,train_qos_mid,mqtt_cat,DISCOVERY,10,955,5.213361,5.222997,5.235389,0
11,train_qos_mid,nmap_10_T5,RECONNAISSANCE,10,425805,55.655757,55.941598,56.189529,0
12,train_qos_mid,nmap_banner,DISCOVERY,9,8188,64.311810,64.352988,64.422614,0
13,train_qos_mid,nmap_mqtt,DISCOVERY,9,8458,242.366493,242.387812,242.485032,0
14,train_qos_mid,nmap_sub,DISCOVERY,12,8753,54.370048,54.400476,55.184246,0
15,train_qos_mid,qos_mid,EXPLOIT,39,12477,0.831616,20.392728,41.984927,0
16,train_qos_mid,qos_mid_ddos,EXPLOIT,75,257148,193.809286,238.170978,296.977965,0
17,train_qos_mid,scp_inst,INSTALLATION,5,267,0.192011,0.194785,0.221114,0
18,train_dollar_char,brute_force_malformed,BRUTE_FORCE,1,15561,893.649952,893.649952,893.649952,0
19,train_dollar_char,dollar_char,EXPLOIT,166,739943,27.281927,49.814458,908.241445,0
20,train_dollar_char,mqtt_cat,DISCOVERY,7,655,5.218077,5.222887,6.112089,0
21,train_dollar_char,nmap_10_T5,RECONNAISSANCE,9,383310,55.733046,55.987157,56.601974,0
22,train_dollar_char,nmap_banner,DISCOVERY,14,12635,64.327948,64.362323,65.231587,0
23,train_dollar_char,nmap_mqtt,DISCOVERY,21,19736,242.366264,242.394832,242.820798,0
24,train_dollar_char,nmap_sub,DISCOVERY,7,5333,54.351879,54.374876,54.752478,0
25,train_dollar_char,scp_inst,INSTALLATION,7,379,0.185556,0.193073,0.195230,0
26,train_slash_char,brute_force_timing,BRUTE_FORCE,1,107510,1047.875183,1047.875183,1047.875183,0
27,train_slash_char,mqtt_cat,DISCOVERY,3,282,5.217969,5.220832,5.221437,0
28,train_slash_char,nmap_10_T4,RECONNAISSANCE,96,4087537,56.151331,56.634234,57.013550,0
29,train_slash_char,nmap_10_T5,RECONNAISSANCE,3,127814,56.221661,56.231167,56.825207,0
30,train_slash_char,nmap_banner,DISCOVERY,3,2728,64.332860,64.343334,65.238320,0
31,train_slash_char,nmap_mqtt,DISCOVERY,3,2839,242.386202,242.413578,242.417577,0
32,train_slash_char,nmap_sub,DISCOVERY,3,2190,54.374007,54.433113,55.133800,0
33,train_slash_char,sftp_inst,INSTALLATION,1,51,0.166788,0.166788,0.166788,0
34,train_slash_char,slash_char,EXPLOIT,243,389562,0.866598,18.697622,52.482464,0
35,train_sub_exf,brute_force_timing,BRUTE_FORCE,1,107640,1060.865450,1060.865450,1060.865450,0
36,train_sub_exf,mqtt_cat,DISCOVERY,27,2550,5.214601,5.221233,6.089434,0
37,train_sub_exf,nmap_10_T5,RECONNAISSANCE,6,255580,55.738719,55.923416,56.427088,0
38,train_sub_exf,nmap_banner,DISCOVERY,88,79052,64.311489,64.348189,65.240955,0
39,train_sub_exf,nmap_mqtt,DISCOVERY,3,2852,242.404704,242.806543,242.875141,0
40,train_sub_exf,nmap_sub,DISCOVERY,93,67366,54.346356,54.381212,55.224129,0
41,train_sub_exf,scp_exf,EXPLOIT,117,5764,0.174348,0.184133,0.223644,0

## 8. Record the smoke review before FULL_DEV

Do this only after both smoke scenarios finish and their scientific checks have been reviewed. Record the rationale and any unresolved choices. This review permits the full development audit; it does not freeze features, pass a modeling gate, or authorize final-test access.

The review binds the exact manifest and report hashes. Changing the manifest invalidates it. Keep `APPROVE_SMOKE=False` until review is complete. To run `FULL_DEV`, return to section 3, change the mode, use the five sources already configured in the manifest, and set `SMOKE_REVIEW_PATH` to the printed path.

In [ ]:
APPROVE_SMOKE = False
REVIEW_NOTES = ""


if APPROVE_SMOKE:
    if MODE != "SMOKE":
        raise ValueError("Create smoke reviews only from SMOKE runs.")
    expected = selected_scenarios(MANIFEST, "SMOKE")
    if set(REPORTS) != set(expected) or any(report["blockers"] for report in REPORTS.values()):
        raise ValueError("Both smoke reports must exist and have no automatic blockers.")
    if not REVIEW_NOTES.strip():
        raise ValueError("Record the review rationale before approval.")
    review = {
        "approved": True,
        "manifest_sha256": sha256_file(MANIFEST_PATH),
        "review_notes": REVIEW_NOTES,
        "reports": {
            scenario: {
                "path": RESULTS[scenario]["report"],
                "sha256": sha256_file(Path(RESULTS[scenario]["report"])),
            }
            for scenario in expected
        },
    }
    review_path = DRIVE_RUN_DIR / "smoke_review.json"
    if review_path.exists():
        raise FileExistsError("A smoke review already exists; preserve the original decision.")
    write_json(review_path, review)
    validate_smoke_review(review_path, sha256_file(MANIFEST_PATH), MANIFEST)
    print(f"Smoke review saved: {review_path}")
else:
    print("Smoke review remains pending. No approval was recorded.")

## 9. Audit the remaining Gate-0 decisions

Run this section only for the completed `FULL_DEV` artifact collection. It reads the persisted audit Parquet files directly from Drive and does not download source CSVs.

The analysis:

- compares normal-packet streams among scenarios that declare the same benign source;
- counts broadcast, multicast, self-loop, IPv4, IPv6, and non-IP packets;
- builds a feature inventory with diagnostic inclusion and exclusion suggestions.

Benign equality uses SHA-256 over an ordered stream of DuckDB 64-bit row hashes computed from every raw column shared within a benign-source group. This is a high-confidence data-level equality diagnostic rather than a byte-for-byte comparison of the original CSV files.

Feature actions are proposals for manual review. Running this section does not freeze the node key, feature schema, sampling policy, or window duration.

In [4]:
decision_test_environment = dict(os.environ)
decision_test_environment["PYTHONPATH"] = str(PROJECT_ROOT / "code/python")
subprocess.run(
    [sys.executable, "-m", "unittest", "discover",
     "-s", str(PROJECT_ROOT / "code/python/tests"),
     "-p", "test_capture_gate0_review.py", "-v"],
    env=decision_test_environment,
    cwd=PROJECT_ROOT,
    check=True,
)

CompletedProcess(args=['/usr/bin/python3', '-m', 'unittest', 'discover', '-s', '/content/temporalgnn-nids/code/python/tests', '-p', 'test_capture_gate0_review.py', '-v'], returncode=0)

In [5]:
from utils import capture_gate0_review

FULL_DEV_RUN_DIR = (
    DRIVE_ROOT / "runs" / "20260917T170658_227477Z_full_dev"
)
DECISION_AUDIT_PATH = FULL_DEV_RUN_DIR / "gate0_decision_audit.json"
DECISION_MODULE_SHA256 = sha256_file(Path(capture_gate0_review.__file__))

if DECISION_AUDIT_PATH.exists():
    DECISION_AUDIT = json.loads(DECISION_AUDIT_PATH.read_text())
    if DECISION_AUDIT["manifest_sha256"] != sha256_file(MANIFEST_PATH):
        raise ValueError("The existing decision audit belongs to a different manifest.")
    if DECISION_AUDIT.get("module_sha256") != DECISION_MODULE_SHA256:
        raise ValueError("The existing decision audit was produced by a different module.")
    print(f"Reusing existing decision audit: {DECISION_AUDIT_PATH}")
else:
    DECISION_AUDIT = capture_gate0_review.run_gate0_decision_audit(
        manifest_path=MANIFEST_PATH,
        run_dir=FULL_DEV_RUN_DIR,
        memory_limit=DUCKDB_MEMORY_LIMIT,
        threads=DUCKDB_THREADS,
    )
    print(f"Decision audit saved: {DECISION_AUDIT_PATH}")

print(f"Decision-audit status: {DECISION_AUDIT['status']}")
print(f"Blockers: {DECISION_AUDIT['blockers']}")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Decision audit saved: /content/drive/MyDrive/capture_gate0/runs/20260917T170658_227477Z_full_dev/gate0_decision_audit.json
Decision-audit status: review_required
Blockers: []

In [6]:
benign_rows = []
for comparison in DECISION_AUDIT["benign_background_comparison"]:
    for scenario, signature in comparison["signatures"].items():
        benign_rows.append({
            "benign_source": comparison["benign_source"],
            "scenario": scenario,
            "all_group_scenarios_identical": comparison[
                "all_benign_packets_identical"
            ],
            "benign_packets": signature["benign_packets"],
            "common_raw_columns": signature["common_raw_columns"],
            "signature": signature[
                "sha256_of_ordered_duckdb_row_hashes"
            ],
        })

topology_rows = []
for item in DECISION_AUDIT["topology"]:
    topology_rows.append({
        key: value
        for key, value in item.items()
        if key != "top_group_destinations"
    })

feature_inventory = pd.DataFrame(
    DECISION_AUDIT["feature_inventory"]
)
feature_review = feature_inventory[
    feature_inventory["suggested_action"] != "candidate_numeric"
][[
    "column",
    "suggested_role",
    "suggested_action",
    "missing_scenarios",
    "missing_values",
    "numeric_when_present",
    "constant_nonmissing_in_each_present_scenario",
]]

print("Benign-background comparison")
display(pd.DataFrame(benign_rows))

print("Topology summary")
display(pd.DataFrame(topology_rows))

print("Top broadcast and multicast destinations")
for item in DECISION_AUDIT["topology"]:
    print(item["scenario"])
    display(pd.DataFrame(item["top_group_destinations"]))

print("Feature action counts")
display(pd.DataFrame(
    sorted(DECISION_AUDIT["feature_action_counts"].items()),
    columns=["suggested_action", "columns"],
))

print("Features requiring exclusion or manual review")
display(feature_review)

Benign-background comparison

,benign_source,scenario,all_group_scenarios_identical,benign_packets,common_raw_columns,signature
0,normal_2_3_4,train_empty_conn,True,746806,107,28bfecad09ed1d4a075471a2edbe71c062fa355d4e6a5e...
1,normal_2_3_4,train_qos_mid,True,746806,107,28bfecad09ed1d4a075471a2edbe71c062fa355d4e6a5e...
2,normal_15_16_17,train_dollar_char,True,1705003,107,5a72511934141b602937a8cfec22b816e69f7e1a561bf2...
3,normal_15_16_17,train_slash_char,True,1705003,107,5a72511934141b602937a8cfec22b816e69f7e1a561bf2...
4,normal_15_16_17,train_sub_exf,True,1705003,107,5a72511934141b602937a8cfec22b816e69f7e1a561bf2...

Topology summary

,scenario,packets,invalid_mac_packets,self_loop_packets,broadcast_destination_packets,multicast_destination_packets,unicast_destination_packets,ipv4_packets,ipv6_packets,non_ip_packets,conflicting_ip_version_packets,arp_protocol_packets,unique_sources,unique_destinations
0,train_empty_conn,1175779,0,0,19805,27000,1128974,1099512,27000,49267,0,49267,131,73
1,train_qos_mid,1499717,0,0,20980,26240,1452497,1426456,26240,47021,0,47021,134,73
2,train_dollar_char,2882555,0,0,26334,23599,2832622,2801360,23599,57596,0,57596,131,73
3,train_slash_char,6425516,0,0,53481,22114,6349921,6320850,22114,82552,0,82552,135,73
4,train_sub_exf,2225807,0,0,94429,22280,2109098,2070845,22280,132682,0,132682,92,73

Top broadcast and multicast destinations
train_empty_conn

          destination  packets
0   33:33:00:00:00:01    24288
1   ff:ff:ff:ff:ff:ff    19805
2   33:33:00:00:00:fb     1537
3   33:33:00:00:00:02      645
4   33:33:00:00:00:16      415
5   33:33:00:00:00:0c       92
6   33:33:ff:09:0c:2c        1
7   33:33:ff:32:5e:9f        1
8   33:33:ff:35:65:f2        1
9   33:33:ff:40:02:8d        1
10  33:33:ff:51:37:08        1
11  33:33:ff:53:10:d0        1
12  33:33:ff:53:d6:db        1
13  33:33:ff:54:62:10        1
14  33:33:ff:78:c5:d1        1
15  33:33:ff:7e:a6:16        1
16  33:33:ff:8e:fc:c6        1
17  33:33:ff:a8:61:93        1
18  33:33:ff:af:82:cc        1
19  33:33:ff:b0:96:9f        1

train_qos_mid

          destination  packets
0   33:33:00:00:00:01    23620
1   ff:ff:ff:ff:ff:ff    20980
2   33:33:00:00:00:fb     1486
3   33:33:00:00:00:02      604
4   33:33:00:00:00:16      415
5   33:33:00:00:00:0c       92
6   33:33:ff:09:0c:2c        1
7   33:33:ff:32:5e:9f        1
8   33:33:ff:35:65:f2        1
9   33:33:ff:40:02:8d        1
10  33:33:ff:51:37:08        1
11  33:33:ff:53:10:d0        1
12  33:33:ff:53:d6:db        1
13  33:33:ff:54:62:10        1
14  33:33:ff:78:c5:d1        1
15  33:33:ff:7e:a6:16        1
16  33:33:ff:8e:fc:c6        1
17  33:33:ff:a8:61:93        1
18  33:33:ff:af:82:cc        1
19  33:33:ff:b0:96:9f        1

train_dollar_char

          destination  packets
0   ff:ff:ff:ff:ff:ff    26334
1   33:33:00:00:00:01    21126
2   33:33:00:00:00:fb     1353
3   33:33:00:00:00:02      587
4   33:33:00:00:00:16      418
5   33:33:00:00:00:0c       92
6   33:33:ff:09:0c:2c        1
7   33:33:ff:32:5e:9f        1
8   33:33:ff:35:65:f2        1
9   33:33:ff:40:02:8d        1
10  33:33:ff:51:37:08        1
11  33:33:ff:53:10:d0        1
12  33:33:ff:53:d6:db        1
13  33:33:ff:54:62:10        1
14  33:33:ff:78:c5:d1        1
15  33:33:ff:7e:a6:16        1
16  33:33:ff:8e:fc:c6        1
17  33:33:ff:a8:61:93        1
18  33:33:ff:af:82:cc        1
19  33:33:ff:b0:96:9f        1

train_slash_char

          destination  packets
0   ff:ff:ff:ff:ff:ff    53481
1   33:33:00:00:00:01    19720
2   33:33:00:00:00:fb     1286
3   33:33:00:00:00:02      575
4   33:33:00:00:00:16      418
5   33:33:00:00:00:0c       92
6   33:33:ff:09:0c:2c        1
7   33:33:ff:32:5e:9f        1
8   33:33:ff:35:65:f2        1
9   33:33:ff:40:02:8d        1
10  33:33:ff:51:37:08        1
11  33:33:ff:53:10:d0        1
12  33:33:ff:53:d6:db        1
13  33:33:ff:54:62:10        1
14  33:33:ff:78:c5:d1        1
15  33:33:ff:7e:a6:16        1
16  33:33:ff:8e:fc:c6        1
17  33:33:ff:a8:61:93        1
18  33:33:ff:af:82:cc        1
19  33:33:ff:b0:96:9f        1

train_sub_exf

          destination  packets
0   ff:ff:ff:ff:ff:ff    94429
1   33:33:00:00:00:01    19860
2   33:33:00:00:00:fb     1313
3   33:33:00:00:00:02      574
4   33:33:00:00:00:16      418
5   33:33:00:00:00:0c       92
6   33:33:ff:09:0c:2c        1
7   33:33:ff:32:5e:9f        1
8   33:33:ff:35:65:f2        1
9   33:33:ff:40:02:8d        1
10  33:33:ff:51:37:08        1
11  33:33:ff:53:10:d0        1
12  33:33:ff:53:d6:db        1
13  33:33:ff:54:62:10        1
14  33:33:ff:78:c5:d1        1
15  33:33:ff:7e:a6:16        1
16  33:33:ff:8e:fc:c6        1
17  33:33:ff:a8:61:93        1
18  33:33:ff:af:82:cc        1
19  33:33:ff:b0:96:9f        1

Feature action counts

                                suggested_action  columns
0                 candidate_categorical_or_mixed       15
1                              candidate_numeric       39
2                  exclude_absolute_time_feature        3
3                    exclude_evaluation_metadata        6
4                        exclude_exact_duplicate        2
5  exclude_primary_review_for_secondary_ablation       10
6                      exclude_record_identifier        2
7                    exclude_schema_inconsistent        1
8                       fit_fold_variance_filter       15
9            topology_only_exclude_model_feature       15

Features requiring exclusion or manual review

,column,suggested_role,suggested_action,missing_scenarios,missing_values,numeric_when_present,constant_nonmissing_in_each_present_scenario
0,label,evaluation_metadata,exclude_evaluation_metadata,[],0,False,False
1,layers__ws.malformed__ws.malformed,candidate_packet_feature,fit_fold_variance_filter,[],14178732,False,True
2,layers_arp_arp.hw.type,candidate_packet_feature,fit_fold_variance_filter,[],13840256,True,True
3,layers_eth_eth.dst,topology_identity,topology_only_exclude_model_feature,[],0,False,False
4,layers_eth_eth.dst_tree_eth.addr,topology_identity,topology_only_exclude_model_feature,[],0,False,False
...,...,...,...,...,...,...,...
103,phase_name,evaluation_metadata,exclude_evaluation_metadata,[],6608621,False,False
104,phase_number,evaluation_metadata,exclude_evaluation_metadata,[],6608621,True,False
105,sequence_id,evaluation_metadata,exclude_evaluation_metadata,[],6608621,True,False
106,step_number,evaluation_metadata,exclude_evaluation_metadata,[],6608621,True,False
107,timestamp,ordering_metadata,exclude_absolute_time_feature,[],0,False,False